'use client';
import {orderNumber} from '@/lib/order-number';
import {useState,useEffect} from 'react';
import {Truck,PackageCheck,Search,Copy,ClipboardCheck,Package,House} from 'lucide-react';
import {useBranding} from '../branding-context';
import {telephone} from '@/lib/branding';
import {paymentStatus} from '@/lib/payment-status';
import {Header,Footer,api} from '../shared';
import {money,statuses} from '@/lib/catalog';
export default function Track(){const brand=useBranding();const [slips,setSlips]=useState<any[]>([]),[token,setToken]=useState(''),[order,setOrder]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
async function find(t:string){setBusy(true);setError('');setOrder(null);try{const d=await api({action:'track',token:t.trim()});setOrder(d.order);setSlips(d.slips||[])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}useEffect(()=>{const t=new URLSearchParams(window.location.search).get('token');if(t){setToken(t);find(t)}},[]);
return <><Header/><main className="container trackpage"><div className="trackintro"><div className="iconcircle"><Truck size={32}/></div><div className="eyebrow">TRACK YOUR ORDER</div><h1>กล่องของคุณ ถึงไหนแล้ว?</h1><p>ใส่รหัสติดตามคำสั่งซื้อที่ได้รับหลังสั่งซื้อ</p></div><form className="tracksearch" onSubmit={e=>{e.preventDefault();find(token)}}><input required minLength={20} aria-label="รหัสติดตามคำสั่งซื้อ" placeholder="รหัสติดตามคำสั่งซื้อ" value={token} onChange={e=>setToken(e.target.value)}/><button className="primary" disabled={busy}><Search size={18}/>{busy?'กำลังค้นหา…':'ติดตาม'}</button></form>{error&&<p className="error" role="alert">{error}</p>}{order&&<section className="panel trackresult"><div className="sectionhead"><div><small>คำสั่งซื้อ</small><h3>{orderNumber(order)}</h3></div><span className="statuspill">{order.status}</span></div><div className="timeline">{['รอยืนยัน','กำลังแพ็ก','จัดส่งแล้ว','ส่งสำเร็จ'].map((s,i)=><div className={['รอยืนยัน','กำลังแพ็ก','จัดส่งแล้ว','ส่งสำเร็จ'].indexOf(['รอชำระเงิน','ชำระแล้ว'].includes(order.status)?'รอยืนยัน':order.status)>=i&&order.status!=='ยกเลิก'?'done':''} key={s}><span>{i===0?<ClipboardCheck/>:i===1?<Package/>:i===2?<Truck/>:<House/>}</span><b>{i===0?'รับคำสั่งซื้อ':s}</b></div>)}</div><div className="trackdetails"><div><small>ขนส่ง</small><b>{order.carrier||'รอร้านจัดส่ง'}</b></div><div><small>เลขพัสดุ</small><b>{order.tracking||'ยังไม่มีเลขพัสดุ'}</b>{order.tracking&&<button className="textbutton" onClick={async()=>{try{await navigator.clipboard.writeText(order.tracking);setCopied(true)}catch{setError('คัดลอกไม่สำเร็จ กรุณาคัดลอกเลขพัสดุด้วยตนเอง')}}}><Copy size={14}/>{copied?'คัดลอกแล้ว':'คัดลอกเลข'}</button>}</div><div><small>ยอดรวม</small><b>฿{money(order.total)}</b></div><div><small>การชำระเงิน</small><b>{paymentStatus(order,slips)}</b></div></div><section className="slipstatus"><h3>หลักฐานชำระเงิน</h3>{slips.length?slips.map((s,i)=><p className="notice" key={i}><b>{s.status}</b> · {new Date(s.created).toLocaleString("th-TH")}<br/>{s.note}</p>):<p className="muted">ยังไม่ได้แนบสลิป</p>}{order.payment!=="ชำระแล้ว"&&order.status!=="ยกเลิก"&&<a className="primary" href={'/payment?token='+token}>ไปหน้าชำระเงิน / แนบสลิป →</a>}</section><p className="notice">สถานะอัปเดตโดยร้านค้า หากมีเลขพัสดุแล้ว สามารถนำเลขไปตรวจสอบกับบริษัทขนส่งได้</p></section>}<div className="trackhelp"><PackageCheck size={24}/><p>ต้องการความช่วยเหลือเกี่ยวกับการจัดส่ง?<br/><a href={telephone(brand.phone)}>โทร. {brand.phone}</a> · {brand.lineUrl?<a href={brand.lineUrl} target="_blank" rel="noreferrer">LINE: {brand.lineId}</a>:<>LINE: {brand.lineId}</>}</p></div></main><Footer/></>}
