'use client';
import {orderNumber} from '@/lib/order-number';
import {useState,useEffect} from 'react';
import {Truck,PackageCheck,Search,Copy,Box,Home,Headphones,MapPin} from 'lucide-react';
import {useBranding} from '../branding-context';
import {telephone} from '@/lib/branding';
import {paymentStatus} from '@/lib/payment-status';
import {Header,Footer,api} from '../shared';
import {money} from '@/lib/catalog';
export default function Track(){const brand=useBranding();const [slips,setSlips]=useState<any[]>([]),[token,setToken]=useState(''),[order,setOrder]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
  async function find(t:string){setBusy(true);setError('');setOrder(null);try{const d=await api({action:'track',token:t.trim()});setOrder(d.order);setSlips(d.slips||[])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  useEffect(()=>{const t=new URLSearchParams(window.location.search).get('token');if(t){setToken(t);find(t)}},[]);
  const stages=['รอยืนยัน','กำลังแพ็ก','จัดส่งแล้ว','ส่งสำเร็จ'];const active=order?stages.indexOf(['รอชำระเงิน','ชำระแล้ว'].includes(order.status)?'รอยืนยัน':order.status):-1;
  return <><Header/><main className="container trackpage fb-track"><div className="trackintro"><div className="iconcircle"><Truck size={32}/></div><div className="eyebrow">TRACK YOUR ORDER</div><h1>กล่องของคุณ ถึงไหนแล้ว?</h1><p>ใส่รหัสคำสั่งซื้อหรือเลขพัสดุ เพื่อตรวจสอบสถานะได้ทันที</p></div><form className="tracksearch" onSubmit={e=>{e.preventDefault();find(token)}}><input required minLength={20} aria-label="รหัสติดตามคำสั่งซื้อ" placeholder="กรอกเลขคำสั่งซื้อ หรือ เลขพัสดุ (Tracking No.)" value={token} onChange={e=>setToken(e.target.value)}/><button className="primary" disabled={busy}><Search size={18}/>{busy?'กำลังค้นหา…':'ติดตาม'}</button></form>{error&&<p className="error" role="alert">{error}</p>}{order&&<section className="panel trackresult"><div className="sectionhead"><div><small>เลขคำสั่งซื้อ</small><h2>{orderNumber(order)}</h2></div><span className="statuspill">{order.status}</span></div><div className="timeline fb-timeline">{stages.map((s,i)=><div className={active>=i&&order.status!=='ยกเลิก'?'done':''} key={s}><span>{i===0?<PackageCheck/>:i===1?<Box/>:i===2?<Truck/>:<Home/>}</span><b>{s==='รอยืนยัน'?'รับคำสั่งซื้อ':s}</b></div>)}</div><div className="trackdetails fb-track-details"><div><small>บริษัทขนส่ง</small><b>{order.carrier||'รอร้านจัดส่ง'}</b></div><div><small>เลขพัสดุ (Tracking No.)</small><b>{order.tracking||'ยังไม่มีเลขพัสดุ'}</b>{order.tracking&&<button className="textbutton" onClick={async()=>{try{await navigator.clipboard.writeText(order.tracking);setCopied(true)}catch{setError('คัดลอกไม่สำเร็จ')}}><Copy size={14}/>{copied?'คัดลอกแล้ว':'คัดลอกเลข'}</button>}</div><div><small>ยอดรวม</small><b>฿{money(order.total)}</b></div><div><small>การชำระเงิน</small><b>{paymentStatus(order,slips)}</b></div></div><section className="slipstatus"><h3>ประวัติการจัดส่ง / ชำระเงิน</h3>{slips.length?slips.map((s,i)=><p className="notice" key={i}><b>{s.status}</b> · {new Date(s.created).toLocaleString('th-TH')}<br/>{s.note}</p>):<p className="muted">รอการอัปเดตจากร้านค้า</p>}{order.payment!=='ชำระแล้ว'&&order.status!=='ยกเลิก'&&<a className="primary" href={'/payment?token='+token}>ไปหน้าชำระเงิน / แนบสลิป →</a>}</section></section>}<div className="fb-track-help"><div><Headphones/><b>มีคำถาม?</b><a href={telephone(brand.phone)}>ติดต่อทีมแอดมิน</a></div><div><PackageCheck/><b>เลขพัสดุใช้ไม่ได้?</b><span>แจ้งปัญหาให้ทีมงาน</span></div><div><MapPin/><b>สอบถามผ่าน LINE</b><span>{brand.lineId}</span></div></div></main><Footer/></>}
