'use client';
import {useEffect,useState} from 'react';
import {Download,Share,Copy,Check,ShoppingBag,Truck,ArrowLeft,Smartphone} from 'lucide-react';
import QRCode from 'qrcode';
import {usePwa} from '../pwa';
export default function InstallPage(){
 const {installed,ready,install}=usePwa();
 const [platform,setPlatform]=useState<'ios'|'android'>('android'),[link,setLink]=useState(''),[qr,setQr]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[insideApp,setInsideApp]=useState(false);
 useEffect(()=>{const ua=navigator.userAgent;setPlatform(/iPad|iPhone|iPod/.test(ua)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1?'ios':'android');setInsideApp(/Line\/|FBAN|FBAV|Instagram/i.test(ua));const url=location.origin+'/install';setLink(url);QRCode.toDataURL(url,{width:240,margin:2,errorCorrectionLevel:'M',color:{dark:'#12483f',light:'#ffffff'}}).then(setQr).catch(()=>{})},[]);
 async function copy(){try{await navigator.clipboard.writeText(link);setMessage('คัดลอกลิงก์แล้ว ส่งให้ลูกค้าได้เลย')}catch{setMessage('แตะค้างที่ช่องลิงก์ด้านล่าง เพื่อเลือกและคัดลอก')}}
 async function share(){try{if(navigator.share)await navigator.share({title:'ติดตั้ง FACTORBOXES',text:'เพิ่มร้านกล่อง FACTORBOXES ลงหน้าจอมือถือ',url:link});else await copy()}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))await copy()}}
 async function runInstall(){if(busy)return;setBusy(true);setMessage('');try{const accepted=await install();setMessage(accepted?'ยืนยันคำขอติดตั้งแล้ว กรุณารอเบราว์เซอร์ดำเนินการ':'ยังไม่ได้ติดตั้ง สามารถทำตามขั้นตอนด้านล่างได้')}finally{setBusy(false)}}
 return <main className="install-page"><a className="install-back" href="/store"><ArrowLeft size={18}/>กลับหน้าร้าน</a><section className="install-card"><img className="install-icon" src="/app-icons/icon-192.png" width="88" height="88" alt="ไอคอน FACTORBOXES"/><p className="install-eyebrow">ร้านกล่อง อยู่ใกล้แค่ปลายนิ้ว</p><h1>เพิ่ม FACTORBOXES<br/>ลงหน้าจอมือถือ</h1><p className="install-intro">กดไอคอนแล้วเข้าร้านได้ทันที<br/>ไม่ต้องค้นหาเว็บใหม่ทุกครั้ง</p><div className="install-features"><span><ShoppingBag/>เลือกซื้อสินค้า</span><span><Truck/>ติดตามพัสดุ</span><span><Smartphone/>ดูออเดอร์เก่า</span></div>
 {installed?<div className="install-success"><Check/>คุณกำลังใช้งานผ่านไอคอนแอปอยู่<a href="/store">เปิดร้านค้า →</a></div>:ready?<button className="install-primary" disabled={busy} onClick={runInstall}><Download size={21}/>{busy?'กำลังเปิดหน้าติดตั้ง…':'ติดตั้ง FACTORBOXES'}</button>:<p className="install-hint">เลือกชนิดมือถือ แล้วทำตามขั้นตอนด้านล่าง</p>}
 {insideApp&&<p className="install-hint">คุณกำลังเปิดผ่านแอปอื่น หากไม่มีเมนูติดตั้ง ให้เปิดลิงก์นี้ใน Safari (iPhone) หรือ Chrome (Android) ก่อน</p>}
 {!installed&&<><div className="install-tabs" role="group" aria-label="เลือกชนิดมือถือ"><button aria-pressed={platform==='ios'} onClick={()=>setPlatform('ios')}>iPhone / iPad</button><button aria-pressed={platform==='android'} onClick={()=>setPlatform('android')}>Android</button></div><ol className="install-steps">{(platform==='ios'?['เปิดหน้านี้ด้วย Safari','แตะปุ่มแชร์ (หรือเมนู ⋯ แล้วเลือก แชร์)','เลือก “เพิ่มไปยังหน้าจอโฮม”','เปิด “เปิดเป็นเว็บแอป” หากมี แล้วแตะ “เพิ่ม”']:['เปิดหน้านี้ด้วย Google Chrome','แตะเมนู ⋮ ที่มุมของเบราว์เซอร์','เลือก “ติดตั้งและสร้างทางลัด” หรือ “เพิ่มลงหน้าจอหลัก”','เลือก “ติดตั้ง” แล้วกดยืนยัน หากมีเฉพาะ “สร้างทางลัด” ก็ใช้เปิดร้านได้']).map((text,i)=><li key={text}><span>{i+1}</span><p>{text}</p></li>)}</ol><p className="install-note">ชื่อเมนูอาจต่างกันตามรุ่นมือถือและเบราว์เซอร์<br/>การซื้อสินค้าและเช็กออเดอร์ต้องเชื่อมต่ออินเทอร์เน็ต</p></>}
 <section className="install-share"><h2>ส่งให้ลูกค้า / สแกนติดตั้ง</h2><p>ใช้ลิงก์เดียวได้ทั้ง iPhone และ Android</p>{qr&&<img className="install-qr" src={qr} width="180" height="180" alt="QR Code สำหรับเปิดหน้าติดตั้ง FACTORBOXES"/>}<input aria-label="ลิงก์ติดตั้งสำหรับลูกค้า" value={link} readOnly onFocus={e=>e.currentTarget.select()}/><div><button onClick={share} disabled={!link}><Share size={18}/>แชร์ลิงก์</button><button onClick={copy} disabled={!link}><Copy size={18}/>คัดลอกลิงก์</button></div>{qr&&<a href={qr} download="factorboxes-install-qr.png">ดาวน์โหลด QR Code</a>}</section><p className="install-message" role="status">{message}</p></section><p className="install-footer"><a href="/guide">ดูใบราคา / ติดต่อร้าน →</a></p><p className="install-footer">FACTORBOXES · โรงงานผลิตกล่องพัสดุ</p></main>
}
