'use client';
import {useEffect,useState} from 'react';
import {money} from '@/lib/catalog';
import {billNumber,dueState,thaiToday} from '@/lib/accounting';
import {orderNumber} from '@/lib/order-number';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import OrderDocuments from './order-documents';
type Row=Record<string,any>;
async function send(body:unknown){const r=await fetch('/api/accounting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d}
const stamp=(s:string)=>s?new Date(s).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}):'—';
const cash=(s:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(s))throw Error('กรอกจำนวนเงินไม่เกิน 2 ตำแหน่งทศนิยม');const [a,b='']=s.split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(n))throw Error('จำนวนเงินไม่ถูกต้อง');return n};
export default function Accounting(){
 const [view,setView]=useState('summary'),[kind,setKind]=useState('expense'),[date,setDate]=useState(thaiToday()),[filter,setFilter]=useState('unpaid'),[search,setSearch]=useState(''),[page,setPage]=useState(0),[tick,setTick]=useState(0),[data,setData]=useState<Row|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState<Row|null>(null),[create,setCreate]=useState(false),[syncing,setSyncing]=useState(false);
 useEffect(()=>{const abort=new AbortController();setBusy(true);setData(null);fetch('/api/accounting?'+new URLSearchParams({view,kind,date,filter,search,page:String(page)}),{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(!abort.signal.aborted)setMessage(e.message)}).finally(()=>{if(!abort.signal.aborted)setBusy(false)});return()=>abort.abort()},[view,kind,date,filter,search,page,tick]);
 useEffect(()=>{let active=true;const sync=()=>{if(document.visibilityState!=='visible')return;send({action:'sync'}).then(()=>{if(active)setTick(n=>n+1)}).catch(e=>{if(active)setMessage(e.message)})};sync();const timer=setInterval(sync,60000);return()=>{active=false;clearInterval(timer)}},[]);
 function nav(v:string,k=kind,f='unpaid'){setView(v);setKind(k);setFilter(f);setPage(0);setSearch('');setMessage('')}
 function changed(){setSelected(null);setCreate(false);setTick(n=>n+1);setMessage('บันทึกบัญชีแล้ว')}
 async function sync(){setSyncing(true);try{const d=await send({action:'sync'});setMessage('ตรวจสอบแล้ว ออกใบวางบิลใหม่ '+d.generated+' ใบ');setTick(n=>n+1)}catch(e){setMessage((e as Error).message)}finally{setSyncing(false)}}
 const totals=data?.balances||[],expense=totals.find((r:Row)=>r.kind==='expense'),income=totals.find((r:Row)=>r.kind==='income');
 return <section className="accounting"><div className="sectionhead"><div><h2>บัญชีและเอกสาร</h2><p className="muted">รับจ่าย · วางบิล · เอกสารส่งนักบัญชี</p></div><button className="secondary" disabled={syncing} onClick={sync}>{syncing?'กำลังตรวจสอบ…':'ตรวจรายการครบกำหนด / ออกใบวางบิล'}</button></div><div className="categoryfilters">{[['summary','ภาพรวม'],['orders','ลูกหนี้ออเดอร์'],['entries','รายรับอื่น / รายจ่าย'],['documents','เอกสาร / ส่งนักบัญชี']].map(([v,label])=><button key={v} aria-pressed={view===v} onClick={()=>nav(v)}>{label}</button>)}</div>{message&&<p className="notice" role="status">{message}</p>}
 <div className="panel form"><div className="accountingfilters">{['summary','documents'].includes(view)?<label>เดือนที่ต้องการดู<input type="month" value={date.slice(0,7)} onChange={e=>{if(e.target.value){setDate(e.target.value+'-01');setPage(0)}}}/></label>:<><label>ค้นหาชื่อ / เลขอ้างอิง<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label>{view==='entries'&&<label>ประเภท<select className="carrier-select" value={kind} onChange={e=>nav('entries',e.target.value)}><option value="expense">รายจ่าย / เจ้าหนี้</option><option value="income">รายรับอื่น (นอกออเดอร์)</option></select></label>}<label>แสดง<select className="carrier-select" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="unpaid">{view==='orders'?'ค้างชำระทั้งหมด':'รายการทั้งหมด'}</option><option value="due">ครบกำหนด / เกินกำหนด</option>{view==='orders'&&<><option value="missing">ยังไม่ตั้งวันครบกำหนด</option><option value="all">ทั้งหมดรวมชำระแล้ว</option></>}</select></label>{view==='entries'&&<button className="primary" onClick={()=>setCreate(true)}>เพิ่ม{kind==='expense'?'รายจ่าย':'รายรับอื่น'}</button>}</>}<button className="secondary" disabled={busy} onClick={()=>setTick(n=>n+1)}>รีเฟรช</button></div>
 {busy&&<p role="status">กำลังโหลด…</p>}
 {data&&view==='summary'&&<><h3>ยอดรับจ่ายเดือน {date.slice(0,7)}</h3><div className="stats"><div><span>รับเงินจากออเดอร์</span><b>฿{money(Number(data.cash?.amount||0))}</b></div><div><span>รับเงินอื่น</span><b>฿{money(Number(data.manual?.find((r:Row)=>r.kind==='income')?.amount||0))}</b></div><div><span>จ่ายเงินแล้ว</span><b>฿{money(Number(data.manual?.find((r:Row)=>r.kind==='expense')?.amount||0))}</b></div><div><span>รับเงิน − จ่ายเงิน</span><b>฿{money(Number(data.cash?.amount||0)+Number(data.manual?.find((r:Row)=>r.kind==='income')?.amount||0)-Number(data.manual?.find((r:Row)=>r.kind==='expense')?.amount||0))}</b><small>ไม่ใช่กำไรสุทธิ</small></div></div>{Number(data.cash?.missing_date)>0&&<p className="notice">มี {data.cash.missing_date} ออเดอร์ไม่ระบุเวลาโอน จึงใช้วันสั่งซื้อชั่วคราว กรุณาแก้เวลาโอนในออเดอร์</p>}<h3>ติดตามครบกำหนด — ยอดคงค้างทุกช่วงเวลา</h3><div className="accountingalerts"><button onClick={()=>nav('orders',kind,'due')}><b>ลูกหนี้ออเดอร์ ฿{money(Number(data.ar?.amount||0))}</b><span>ต้องติดตามวันนี้ / เกินกำหนด {data.ar?.due||0} รายการ →</span></button><button onClick={()=>nav('entries','expense','due')}><b>เจ้าหนี้ ฿{money(Number(expense?.amount||0))}</b><span>ต้องจ่ายวันนี้ / เกินกำหนด {expense?.due||0} รายการ →</span></button><button onClick={()=>nav('entries','income','due')}><b>รายรับอื่นค้าง ฿{money(Number(income?.amount||0))}</b><span>ต้องติดตาม {income?.due||0} รายการ →</span></button></div><h3>ภาษีตามวันที่เอกสารเดือนนี้</h3><p>VAT จากใบกำกับที่ออก: <b>฿{money(Number(data.taxes?.vat||0))}</b> ({data.taxes?.n||0} ใบ)</p><p>VAT ตามเอกสารรายจ่ายที่กรอก: <b>฿{money(Number(data.purchase?.vat||0))}</b></p><small className="muted">ใช้ส่งนักบัญชีตรวจสอบ ยังไม่หักเป็นภาษีที่ต้องนำส่ง และไม่ใช่งบการเงิน ออเดอร์ที่ยืนยันรับเงินแล้วจะตัดออกจากลูกหนี้อัตโนมัติ</small></>}
 {data&&view==='orders'&&<><p className="muted">ตั้งวันครบกำหนดเพื่อให้ระบบออกใบวางบิลเมื่อถึงวันนั้น กรอกชื่อและที่อยู่บริษัทในตั้งค่าร้านก่อนออกใบวางบิล การรับเงินออเดอร์ยืนยันเต็มยอดตามระบบเดิม</p><Grid headers={['ออเดอร์ / ลูกค้า','ยอดคงค้าง','ครบกำหนด / ผู้รับผิดชอบ','สถานะ','']} rows={data.rows.map((o:Row)=><tr key={o.id}><td><b>{orderNumber({id:o.id,order_no:o.order_no})}</b><small>{o.customer}<br/>{o.phone}</small></td><td>฿{money(o.payment==='ชำระแล้ว'?0:Number(o.total))}</td><td>{o.due_date||'ยังไม่ตั้ง'}<small>{o.assignee||'ไม่ระบุผู้รับผิดชอบ'}</small></td><td>{dueState(o.due_date,o.payment==='ชำระแล้ว'?0:Number(o.total))}{o.bill_id&&<small><a href={'/accounting/print?bill='+o.bill_id} target="_blank" rel="noreferrer">{billNumber(o.bill_id)} ↗</a></small>}</td><td><button className="textbutton" onClick={()=>setSelected({...o,_kind:'order'})}>จัดการ / ติดตาม →</button></td></tr>)}/></>}
 {data&&view==='entries'&&<><p className="muted">รายรับอื่นใช้เฉพาะรายการนอกออเดอร์ เพื่อไม่ให้นับรายรับออเดอร์ซ้ำ</p><Grid headers={['คู่ค้า / เอกสาร','ยอดรวม / ชำระแล้ว','คงเหลือ','ครบกำหนด','']} rows={data.rows.map((e:Row)=><tr key={e.id}><td><b>{e.counterparty}</b><small>{e.reference||'ไม่มีเลขอ้างอิง'} · {e.category}</small></td><td>฿{money(Number(e.amount))}<small>ชำระแล้ว ฿{money(Number(e.paid))}</small></td><td>฿{money(Number(e.balance))}</td><td>{e.due_date}<small>{dueState(e.due_date,Number(e.balance))}</small></td><td><button className="textbutton" onClick={()=>setSelected({...e,_kind:'entry'})}>จัดการ →</button></td></tr>)}/></>}
 {data&&view==='documents'&&<><Export date={date}/><p className="muted">เอกสารเดิมเชื่อมเข้าทะเบียนอัตโนมัติ ไม่ต้องกรอกซ้ำ ใบเสร็จและใบกำกับของออเดอร์เดียวกันไม่ใช่รายได้สองรายการ</p><Grid headers={['เลขเอกสาร','วันที่ออก','ลูกค้า','ยอดเอกสาร','']} rows={data.rows.map((d:Row)=><tr key={d.id}><td>{d.type==='tax'?'TAX-':'RC-'}{String(d.id).padStart(7,'0')}</td><td>{stamp(d.created)}</td><td>{d.customer}</td><td>฿{money(Number(d.total))}</td><td><a className="textbutton" href={'/accounting/print?doc='+d.id} target="_blank" rel="noreferrer">พิมพ์ / บันทึก PDF ↗</a></td></tr>)}/></>}
 {data&&view!=='summary'&&<div className="accountingfilters"><button className="secondary" disabled={!page} onClick={()=>setPage(n=>n-1)}>ก่อนหน้า</button><span>หน้า {page+1} · หน้าละ 50 รายการ</span><button className="secondary" disabled={!data.more} onClick={()=>setPage(n=>n+1)}>ถัดไป</button></div>}</div>
 <Sheet open={!!selected||create} onOpenChange={v=>{if(!v){setSelected(null);setCreate(false)}}}><SheetContent className="cartdrawer"><SheetHeader><SheetTitle>{create?'เพิ่มรายการบัญชี':selected?._kind==='order'?'บัญชีออเดอร์ '+orderNumber(selected as any):'รายละเอียดบัญชี'}</SheetTitle><SheetDescription>ตรวจสอบเอกสารและจำนวนเงินก่อนบันทึก</SheetDescription></SheetHeader><div className="cartcontent form">{create?<EntryForm kind={kind} onDone={changed}/>:selected&&<Detail key={selected.id} item={selected} onDone={changed}/>}</div></SheetContent></Sheet>
 </section>
}
function Grid({headers,rows}:{headers:string[],rows:React.ReactNode[]}){return <div className="accountingtable"><table><thead><tr>{headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={headers.length}>ไม่มีรายการในช่วงนี้</td></tr>}</tbody></table></div>}
function Export({date}:{date:string}){const [from,setFrom]=useState(date.slice(0,7)+'-01'),[through,setThrough]=useState(date),[images,setImages]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{setFrom(date.slice(0,7)+'-01');const d=new Date(date.slice(0,7)+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);setThrough(d.toISOString().slice(0,10))},[date]);async function download(){setBusy(true);setError('');try{const r=await fetch('/api/accounting/export?'+new URLSearchParams({from,through,images:images?'1':'0'}));if(!r.ok){const d=await r.json();throw Error(d.error)}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`FACTORBOXES-accounting-${from}-${through}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <section className="form"><h3>ดาวน์โหลดชุดเอกสารส่งนักบัญชี</h3><div className="accountingfilters"><label>ตั้งแต่<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>ถึง<input type="date" value={through} onChange={e=>setThrough(e.target.value)}/></label><label className="checkline"><input type="checkbox" checked={images} onChange={e=>setImages(e.target.checked)}/>รวมภาพเอกสารแนบ</label><button className="primary" disabled={busy} onClick={download}>{busy?'กำลังเตรียมไฟล์…':'ดาวน์โหลด ZIP'}</button></div><small>รวม CSV เปิดใน Excel ได้ และใบเสร็จ/ใบกำกับ/ใบวางบิลที่เปิดดูและบันทึกเป็น PDF ได้ ไม่ต้องเข้าสู่ระบบ · ภาพแนบเลือกตามวันที่เอกสาร</small>{error&&<p className="notice" role="alert">{error}</p>}</section>}
function EntryForm({kind,onDone}:{kind:string,onDone:()=>void}){const [form,setForm]=useState({id:crypto.randomUUID(),kind,document_date:thaiToday(),due_date:thaiToday(),counterparty:'',reference:'',category:kind==='expense'?'ค่าใช้จ่ายทั่วไป':'รายรับอื่น',description:'',amount:'',vat:'0',assignee:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await send({...form,action:'entry',amount:cash(form.amount),vat:cash(form.vat)});onDone()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><p>{kind==='expense'?'รายจ่าย / เจ้าหนี้':'รายรับอื่นที่ไม่ใช่ออเดอร์'}</p>{([['document_date','วันที่เอกสาร'],['due_date','วันครบกำหนด'],['counterparty','ชื่อลูกค้า / ผู้ขาย'],['reference','เลขที่เอกสารอ้างอิง'],['category','หมวดบัญชี'],['description','รายละเอียด'],['amount','ยอดรวม VAT (บาท)'],['vat','VAT ตามเอกสาร (บาท)'],['assignee','ผู้รับผิดชอบ']] as const).map(([key,label])=><label key={key}>{label}<input required={!['reference','assignee'].includes(key)} type={key.includes('date')?'date':'text'} inputMode={['amount','vat'].includes(key)?'decimal':undefined} value={form[key]} maxLength={key==='description'?1000:200} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<p className="muted">หลังบันทึก ให้เปิดรายการเพื่อแนบภาพเอกสารและลงการรับ/จ่ายเงิน หากกรอกยอดผิดให้ยกเลิกรายการแล้วสร้างใหม่เพื่อเก็บประวัติ</p>{error&&<p role="alert" className="notice">{error}</p>}<button className="primary" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึกรายการบัญชี'}</button></form>}
function Detail({item,onDone}:{item:Row,onDone:()=>void}){
 const order=item._kind==='order';const [due,setDue]=useState(item.due_date||thaiToday()),[assignee,setAssignee]=useState(item.assignee||''),[memo,setMemo]=useState(item.note||''),[note,setNote]=useState(''),[detail,setDetail]=useState<Row>({notes:[],payments:[],files:[]}),[tick,setTick]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[amount,setAmount]=useState(order?money(Number(item.total)).replaceAll(',',''):(Number(item.balance)/100).toFixed(2)),[paidAt,setPaidAt]=useState(new Date(Date.now()+7*3600000).toISOString().slice(0,16)),[reference,setReference]=useState(''),[paymentId]=useState(crypto.randomUUID()),[reason,setReason]=useState('');
 useEffect(()=>{const c=new AbortController();fetch('/api/accounting?'+new URLSearchParams({view:'detail',kind:item._kind,id:item.id}),{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setDetail(d)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[item.id,item._kind,tick]);
 async function action(body:Row,close=true){setBusy(true);setError('');try{await send(body);if(close)onDone();else{setNote('');setTick(n=>n+1)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><h3>{item.customer||item.counterparty}</h3><p>{item.description||item.phone}</p><p>ยอดรวม ฿{money(Number(item.total||item.amount))}</p>{error&&<p role="alert" className="notice">{error}</p>}{order&&<form className="form" onSubmit={e=>{e.preventDefault();action({action:'terms',order:item.id,due_date:due,assignee,note:memo})}}><label>วันครบกำหนด<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>ผู้รับผิดชอบ<input maxLength={100} value={assignee} onChange={e=>setAssignee(e.target.value)}/></label><label>หมายเหตุเครดิต<textarea maxLength={1000} value={memo} onChange={e=>setMemo(e.target.value)}/></label><small>หากเปลี่ยนวันครบกำหนด ใบวางบิลเดิมจะถูกยกเลิกและเก็บประวัติ ระบบออกใบใหม่เมื่อถึงกำหนดใหม่</small><button className="primary" disabled={busy}>บันทึกกำหนดวางบิล</button>{item.bill_id&&<a className="secondary" target="_blank" rel="noreferrer" href={'/accounting/print?bill='+item.bill_id}>เปิด {billNumber(item.bill_id)} / PDF ↗</a>}</form>}
 {(order?item.payment!=='ชำระแล้ว':Number(item.balance)>0)&&<form className="form" onSubmit={e=>{e.preventDefault();try{action(order?{action:'order-payment',order:item.id,paid_at:new Date(paidAt+':00+07:00').toISOString()}:{action:'payment',id:paymentId,entry:item.id,amount:cash(amount),paid_at:new Date(paidAt+':00+07:00').toISOString(),reference})}catch(e){setError((e as Error).message)}}}><h3>{order?'ยืนยันรับเงินออเดอร์เต็มยอด':item.kind==='expense'?'บันทึกจ่ายเงิน':'บันทึกรับเงิน'}</h3>{!order&&<label>จำนวนเงิน (บาท) · คงเหลือ {money(Number(item.balance))}<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label>}<label>วันเวลาชำระ (ประเทศไทย)<input required type="datetime-local" value={paidAt} onChange={e=>setPaidAt(e.target.value)}/></label>{!order&&<label>อ้างอิงการโอน<input maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label>}<label className="checkline"><input type="checkbox" required/>ตรวจสอบรับ/จ่ายเงินจริงแล้ว</label><button className="primary" disabled={busy}>ยืนยันบันทึก{order?'เต็มยอด ฿'+money(Number(item.total)):''}</button></form>}
 {!order&&<><h3>ภาพเอกสาร / หลักฐานรับจ่าย</h3><label>แนบภาพ (สูงสุด 5 รูป)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setBusy(true);setError('');try{const form=new FormData();form.set('entry',item.id);form.set('file',f);const r=await fetch('/api/accounting/file',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error);setTick(n=>n+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/></label><small>JPG, PNG, WEBP ไม่เกิน 4 MB ต่อภาพ</small>{detail.files.map((f:Row,i:number)=><a key={f.id} href={'/api/accounting/file?id='+f.id}>ดาวน์โหลดภาพเอกสาร {i+1} ↗</a>)}<h3>ประวัติชำระเงิน</h3>{detail.payments.map((p:Row)=><div className="notice" key={p.id}><b>฿{money(Number(p.amount))}</b> · {stamp(p.paid_at)}<p>{p.reference} · {p.actor}</p>{p.voided_at?<p>ยกเลิก: {p.void_reason}</p>:<button disabled={busy||reason.trim().length<3} className="textbutton" onClick={()=>action({action:'void-payment',id:p.id,reason})}>ยกเลิกการชำระนี้ (ต้องระบุเหตุผลด้านล่าง)</button>}</div>)}</>}
 <h3>ติดตามการชำระ / บันทึกพนักงาน</h3><form className="form" onSubmit={e=>{e.preventDefault();action({action:'note',id:item.id,kind:item._kind,note},false)}}><textarea required maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="เช่น โทรแจ้งยอดแล้ว ลูกค้านัดโอนวันศุกร์"/><button className="secondary" disabled={busy}>บันทึกการติดตาม</button></form>{detail.notes.map((n:Row,i:number)=><div className="notice" key={i}><p className="preline">{n.note}</p><small>{stamp(n.created_at)} · {n.actor}</small></div>)}
 {order?<OrderDocuments orderId={item.id}/>:<section className="form"><h3>ยกเลิกรายการที่กรอกผิด</h3><label>เหตุผลยกเลิก<textarea minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="secondary" disabled={busy||reason.trim().length<3||Number(item.paid)>0} onClick={()=>action({action:'void-entry',id:item.id,reason})}>ยกเลิกรายการบัญชีนี้</button><small>ต้องยกเลิกการชำระทั้งหมดก่อนยกเลิกรายการ ประวัติเดิมยังอยู่ในชุดส่งออก</small></section>}
 </>
}
