'use client';
import {useEffect,useState} from 'react';
import {pageLabels} from '@/lib/analytics';
type Counts={views:number,visitors:number};
type Report={totals:Counts,rows:(Counts&{day:string})[],pages:(Counts&{path:string})[],range:{from:string,through:string}};
export default function Analytics(){const [period,setPeriod]=useState('month'),[date,setDate]=useState(new Date(Date.now()+7*3600000).toISOString().slice(0,10)),[refresh,setRefresh]=useState(0),[data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const abort=new AbortController();setBusy(true);setError('');setData(null);fetch('/api/analytics?'+new URLSearchParams({period,date}),{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)}).finally(()=>{if(!abort.signal.aborted)setBusy(false)});return()=>abort.abort()},[period,date,refresh]);
 const num=(n:number)=>Number(n).toLocaleString('th-TH');
 return <section className="panel form"><h3>สถิติคนเข้าเว็บไซต์</h3><div style={{display:'flex',flexWrap:'wrap',gap:16,alignItems:'end'}}><label>ช่วงเวลา<select className="carrier-select" value={period} onChange={e=>setPeriod(e.target.value)}>{Object.entries({day:'รายวัน',week:'รายสัปดาห์',month:'รายเดือน',year:'รายปี'}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>วันที่อ้างอิง<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button type="button" className="secondary" disabled={busy} onClick={()=>setRefresh(n=>n+1)}>รีเฟรชสถิติ</button></div><p className="muted">นับเฉพาะหน้าร้านและหน้าสมาชิก ไม่รวมหลังบ้าน เริ่มเก็บหลังติดตั้งระบบนี้ · เวลาไทย</p>{busy&&<p role="status">กำลังโหลด…</p>}{error&&<p className="notice" role="alert">{error}</p>}{data&&<><p>{data.range.from} ถึง {data.range.through}</p><div className="stats"><div><span>ผู้เข้าชมโดยประมาณ</span><b>{num(data.totals.visitors)}</b><small>เบราว์เซอร์ไม่ซ้ำในช่วงที่เลือก</small></div><div><span>จำนวนเปิดหน้าเว็บ</span><b>{num(data.totals.views)}</b><small>รวมทุกหน้าที่ติดตาม</small></div></div>{!Number(data.totals.views)&&<p className="notice">ยังไม่มีผู้เข้าชมในช่วงนี้ ลองเปิดหน้าร้านแล้วกลับมารีเฟรชสถิติ</p>}<h3>หน้าที่มีคนเปิดดูมากที่สุด</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>หน้าเว็บ</th><th>เปิดดู (ครั้ง)</th><th>ผู้เข้าชม</th></tr></thead><tbody>{data.pages.map(p=><tr key={p.path}><td>{pageLabels[p.path]||p.path}</td><td>{num(p.views)}</td><td>{num(p.visitors)}</td></tr>)}</tbody></table></div><h3>สถิติรายวัน</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>วันที่</th><th>เปิดดู (ครั้ง)</th><th>ผู้เข้าชม</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.day}><td>{r.day}</td><td>{num(r.views)}</td><td>{num(r.visitors)}</td></tr>)}</tbody></table></div></>}<small className="muted">ผู้เข้าชมใช้รหัสสุ่มของเบราว์เซอร์ จึงไม่ใช่จำนวนคนจริงที่ยืนยันตัวตน การเปลี่ยนเครื่องหรือล้างข้อมูลอาจนับเป็นคนใหม่ ไม่นับการเปิดหน้าเดิมซ้ำภายใน 30 วินาที และไม่นับเบราว์เซอร์ที่ปิดการติดตาม (Do Not Track) หรือไม่อนุญาตให้บันทึกรหัส ไม่เก็บชื่อ อีเมล IP หรือเลขติดตามพัสดุในสถิตินี้</small></section>
}
