'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ImageIcon,MessageCircle,Monitor,Phone,Save,Smartphone,UploadCloud} from 'lucide-react';
import {defaultBranding} from '@/lib/branding';
export default function BrandingEditor(){
 const [form,setForm]=useState(defaultBranding),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState('');
 const [dimensions,setDimensions]=useState<{width:number;height:number}|null>(null);const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/branding',{signal:c.signal}).then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);setForm({...defaultBranding,...d.branding});setLoaded(true)}).catch(e=>{if(e.name!=='AbortError')setMessage(e.message)});return()=>c.abort()},[]);
 useEffect(()=>{setDimensions(null)},[form.bannerImage]);
 async function upload(files:FileList|null){if(!files?.[0]||uploading)return;setUploading(true);setMessage('');try{const image=files[0];if(!['image/jpeg','image/png','image/webp'].includes(image.type)||!image.size||image.size>4*1024*1024)throw Error('เลือกภาพ JPG, PNG หรือ WEBP ขนาดไม่เกิน 4 MB');const f=new FormData();f.set('file',image);const r=await fetch('/api/branding',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw Error(d.error);setForm(p=>({...p,bannerImage:d.id,bannerMode:'image'}));setMessage('อัปโหลดแล้ว ตรวจรูปตัวอย่างและกดบันทึกเพื่อแสดงบนหน้าร้าน')}catch(e){setMessage((e as Error).message)}finally{setUploading(false);if(file.current)file.current.value=''}}
 async function save(e:React.FormEvent){e.preventDefault();if(busy||uploading)return;setBusy(true);setMessage('');try{const r=await fetch('/api/branding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage('บันทึกหน้าร้านแล้ว เปิดหรือรีเฟรชหน้าร้านเพื่อดูข้อมูลใหม่');window.dispatchEvent(new Event('branding-updated'))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <form className="admin-branding-editor" onSubmit={save}>
  <div className="admin-branding-columns"><div>
   <section className="admin-branding-card"><h2><ImageIcon size={22}/>รูปแบนเนอร์ / โปรโมชั่น</h2><p>เลือกภาพโปรใหม่สำหรับแสดงบนหน้าร้าน</p>
    <label>รูปแบบแบนเนอร์<select aria-label="รูปแบบแบนเนอร์" value={form.bannerMode} onChange={e=>setForm({...form,bannerMode:e.target.value as 'designed'|'image'})}><option value="designed">แบนเนอร์ข้อความของร้าน</option><option value="image">ใช้รูปแบนเนอร์ / โบรชัวร์</option></select></label>
    <div className="admin-banner-size-guide"><h3>ขนาดภาพแนะนำสำหรับออกแบบ</h3><div><article><Monitor size={25}/><span>แบนเนอร์แนวนอน</span><strong>1,600 × 400 <small>px</small></strong><small>กว้าง × สูง · อัตราส่วน 4:1</small></article><article><Smartphone size={25}/><span>โบรชัวร์แนวตั้ง</span><strong>1,080 × 1,350 <small>px</small></strong><small>กว้าง × สูง · อัตราส่วน 4:5</small></article></div><p>ภาพย่อตามความกว้างจอและคงสัดส่วนเดิม ไม่ตัดข้อความ เลือกขนาดให้ตรงกับรูปแบบโปรที่ต้องการ</p></div>
    <label className="admin-banner-upload"><UploadCloud size={31}/><b>{uploading?'กำลังอัปโหลด…':'เลือกรูปแบนเนอร์ใหม่'}</b><span>JPG, PNG, WEBP · ไม่เกิน 4 MB</span><input ref={file} aria-label="อัปโหลดรูปแบนเนอร์" type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading||busy||!loaded} onChange={e=>upload(e.target.files)}/></label>
    {form.bannerImage?<><div className="admin-banner-preview"><span>ตัวอย่างภาพที่เลือก</span><img src={'/api/branding?image='+form.bannerImage} alt={form.bannerAlt||'ตัวอย่างแบนเนอร์'} onLoad={e=>setDimensions({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})} onError={()=>{setDimensions(null);setMessage('โหลดตัวอย่างภาพไม่สำเร็จ กรุณาตรวจรูปหรือลองอัปโหลดใหม่')}}/>{dimensions&&<small>ขนาดจริง: กว้าง {dimensions.width.toLocaleString()} × สูง {dimensions.height.toLocaleString()} พิกเซล</small>}</div><button type="button" className="admin-text-button" onClick={()=>setForm({...form,bannerImage:'',bannerMode:'designed'})}>นำรูปนี้ออกจากแบนเนอร์</button></>:<div className="admin-banner-empty"><ImageIcon size={25}/><span>ยังไม่ได้เลือกรูป ใช้แบนเนอร์ข้อความของร้านได้</span></div>}
    <label>คำอธิบายรูป<input required maxLength={200} value={form.bannerAlt} onChange={e=>setForm({...form,bannerAlt:e.target.value})}/></label>
    <p className="admin-branding-hint">หากรูปมี LINE เบอร์โทร หรือราคาอยู่ในภาพ ให้อัปโหลดภาพที่แก้แล้ว ข้อมูลในภาพจะไม่เปลี่ยนตามช่องข้อความ</p>
   </section>
  </div><div>
   <section className="admin-branding-card"><h2><Phone size={21}/>ช่องทางติดต่อร้าน</h2><label>เบอร์โทรศัพท์<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>LINE ID / ชื่อ LINE<input required value={form.lineId} onChange={e=>setForm({...form,lineId:e.target.value})}/></label><label>ลิงก์เพิ่มเพื่อน LINE (ถ้ามี)<input type="url" value={form.lineUrl} placeholder="https://lin.ee/…" onChange={e=>setForm({...form,lineUrl:e.target.value})}/></label><label>ข้อความแถบบนสุด<input value={form.announcement} maxLength={200} onChange={e=>setForm({...form,announcement:e.target.value})}/></label></section>
   <section className="admin-branding-card"><h2><MessageCircle size={21}/>ข้อความและปุ่มโปรโมชั่น</h2>{([['eyebrow','ข้อความเหนือหัวข้อ'],['headline','หัวข้อแบนเนอร์'],['description','รายละเอียดโปรโมชั่น'],['promoTitle','ข้อความโปรส่งฟรี'],['promoNote','ข้อความใต้ภาพ'],['buttonText','ข้อความปุ่ม'],['buttonUrl','ลิงก์ปุ่ม']] as const).map(([key,label])=><label key={key}>{label}{['headline','description'].includes(key)?<textarea rows={2} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<p className="admin-branding-hint">ข้อความโปรไม่เปลี่ยนยอดคิดเงินจริง ตั้งยอดส่งฟรีที่ “ตั้งค่าร้านค้า” และส่วนลดที่ “โปรโมชั่น / CODE”</p></section>
  </div></div>
  {message&&<p className="admin-feedback" role="status">{message}</p>}
  <div className="admin-branding-save"><a className="admin-outline" href="/store" target="_blank" rel="noreferrer">ดูหน้าร้าน<ArrowUpRight size={18}/></a><button className="admin-primary" disabled={busy||uploading||!loaded}><Save size={18}/>{uploading?'กำลังอัปโหลด…':busy?'กำลังบันทึก…':'บันทึกแบนเนอร์และข้อมูลติดต่อ'}</button></div>
 </form>
}
