'use client';
import {useEffect,useState} from 'react';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
export default function DeleteOrder({orderId}:{orderId:string}){
 const [allowed,setAllowed]=useState(false),[open,setOpen]=useState(false),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[deleted,setDeleted]=useState(false);
 const number='FB-'+orderId.slice(0,8).toUpperCase();
 useEffect(()=>{const c=new AbortController();fetch('/api/delete-order',{signal:c.signal,cache:'no-store'}).then(async r=>{if(r.ok)setAllowed((await r.json()).canDelete===true)}).catch(()=>{});return ()=>c.abort()},[]);
 async function remove(){if(busy||confirmation.trim()!==number)return;setBusy(true);setMessage('');try{const r=await fetch('/api/delete-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:orderId,confirmation})});const d=await r.json();if(!r.ok)throw Error(d.error||'ลบไม่สำเร็จ');setDeleted(true);if(d.warning)setMessage(d.warning);else window.location.reload()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 if(!allowed)return null;
 return <section className="form"><h3>ลบออเดอร์ทดลอง</h3><p className="muted">ลบออเดอร์ที่ไม่ต้องการออกจากประวัติและยอดขาย</p><AlertDialog open={open} onOpenChange={v=>{if(!busy&&!deleted){setOpen(v);setConfirmation('');setMessage('')}}}><AlertDialogTrigger asChild><button type="button" className="secondary" style={{color:'#b42318',borderColor:'#b42318'}}>ลบออเดอร์นี้</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>ลบออเดอร์ {number}?</AlertDialogTitle><AlertDialogDescription>ออเดอร์นี้จะถูกลบถาวร พร้อมใบเสร็จ ใบกำกับภาษี และสลิปที่เกี่ยวข้อง ยอดขายและ VAT ของออเดอร์นี้จะถูกนำออกจากรายงาน ไม่สามารถกู้คืนผ่านหน้าเว็บได้</AlertDialogDescription></AlertDialogHeader><label className="form">พิมพ์ {number} เพื่อยืนยัน<input value={confirmation} disabled={busy||deleted} onChange={e=>setConfirmation(e.target.value.toUpperCase())} autoComplete="off" spellCheck={false} aria-label="เลขออเดอร์ยืนยันลบ"/></label>{message&&<p className="notice" role="status">{message}</p>}<AlertDialogFooter>{deleted?<button className="primary" onClick={()=>window.location.reload()}>กลับไปดูยอดขายล่าสุด</button>:<><AlertDialogCancel disabled={busy}>ยกเลิก</AlertDialogCancel><button type="button" className="primary" style={{background:'#b42318'}} disabled={busy||confirmation.trim()!==number} onClick={remove}>{busy?'กำลังลบ…':'ยืนยันลบถาวร'}</button></>}</AlertDialogFooter></AlertDialogContent></AlertDialog></section>
}
