'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Check,ExternalLink,FileText,MapPin,Package,Printer,Save,Truck,Wallet} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {orderNumber} from '@/lib/order-number';
import {money,statuses} from '@/lib/catalog';
import {paymentDate} from '@/lib/payment-view';
import {orderItems,type AdminOrder,type OrderSection} from '@/lib/admin-orders';
import {StatusBadge} from './orders';
import SlipReview from './slip-review';
import OrderDocuments from './order-documents';
type Props={order:AdminOrder|null;section:OrderSection;carriers:string[];onClose:()=>void;onSave:(order:AdminOrder)=>Promise<AdminOrder|null>;onReload:()=>Promise<void>};
export default function OrderDetail({order,section,carriers,onClose,onSave,onReload}:Props){
 const [draft,setDraft]=useState(order),[tab,setTab]=useState<OrderSection>(section),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{setDraft(order)},[order]);useEffect(()=>{setTab(section);setMessage('')},[order?.id,section]);
 const dirty=JSON.stringify(draft)!==JSON.stringify(order);
 const patch=(values:Partial<AdminOrder>)=>setDraft(previous=>previous?{...previous,...values}:previous);
 async function save(){if(!draft||busy)return;setBusy(true);setMessage('');try{const saved=await onSave(draft);if(saved){setDraft(saved);setMessage('บันทึกออเดอร์แล้ว')}}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const items=draft?orderItems(draft):[];
 return <Sheet open={!!order} onOpenChange={open=>{if(!open)onClose()}}><SheetContent className="admin-order-drawer"><SheetHeader><SheetTitle>จัดการออเดอร์ <span>{order&&orderNumber(order)}</span></SheetTitle><SheetDescription>{order?paymentDate(order.created)+' น.':'รายละเอียดคำสั่งซื้อ'}</SheetDescription></SheetHeader>{draft&&<><div className="admin-drawer-summary"><div><b>{draft.customer}</b><span>{draft.phone}</span></div><strong>฿{money(draft.total)}</strong><div><StatusBadge order={order||draft} payment/><StatusBadge order={order||draft}/></div></div><nav className="admin-drawer-tabs" aria-label="ส่วนจัดการออเดอร์">{([{key:'details',label:'รายละเอียด',icon:Package},{key:'payment',label:'ตรวจชำระ',icon:Wallet},{key:'shipping',label:'การจัดส่ง',icon:Truck},{key:'documents',label:'พิมพ์เอกสาร',icon:Printer}] as const).map(({key,label,icon:Icon})=><button type="button" key={key} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}><Icon size={17}/>{label}</button>)}</nav><div className="admin-drawer-body">
  {dirty&&<p className="admin-feedback">มีการแก้ไขที่ยังไม่บันทึก กด “บันทึกออเดอร์” ก่อนพิมพ์ข้อมูลล่าสุด</p>}
  {tab==='details'&&<><section className="admin-detail-section"><h3><MapPin size={19}/>ข้อมูลผู้รับ</h3><b>{draft.customer}</b><p>{draft.phone}</p><p className="preline">{draft.address}</p></section><section className="admin-detail-section"><h3><Package size={19}/>รายการสินค้า <small>{items.reduce((s,i)=>s+i.qty,0).toLocaleString()} ชิ้น</small></h3>{items.map((item,i)=><div className="admin-detail-item" key={item.id+'-'+i}><span>{item.name}<small>{item.qty.toLocaleString()} × ฿{money(item.price)}</small></span><b>฿{money(item.price*item.qty)}</b></div>)}</section><section className="admin-detail-totals"><div><span>ยอดสินค้าตามเรท</span><b>฿{money(draft.subtotal+(draft.coupon_discount||0))}</b></div>{draft.coupon_discount>0&&<div><span>CODE {draft.coupon_code}</span><b>−฿{money(draft.coupon_discount)}</b></div>}<div><span>สินค้าก่อน VAT</span><b>฿{money(draft.subtotal-draft.vat)}</b></div><div><span>VAT สินค้า</span><b>฿{money(draft.vat)}</b></div><div><span>ค่าจัดส่ง</span><b>฿{money(draft.shipping)}</b></div><div className="grand"><span>ยอดรวมทั้งสิ้น</span><b>฿{money(draft.total)}</b></div></section><button className="admin-primary" onClick={()=>setTab(order?.payment==='ชำระแล้ว'?'shipping':'payment')}>{order?.payment==='ชำระแล้ว'?'จัดการการจัดส่ง':'ตรวจสอบการชำระเงิน'}<ArrowRight size={18}/></button></>}
  {tab==='payment'&&<><section className="admin-detail-section"><SlipReview key={draft.id} orderId={draft.id} onReviewed={()=>{void onReload()}}/></section><section className="admin-detail-section admin-field-grid"><h3>บันทึกการรับเงิน</h3><label>สถานะการชำระ<select aria-label="การชำระเงิน" value={draft.payment} onChange={e=>patch({payment:e.target.value})}><option value="รอชำระ">รอชำระ</option><option value="ชำระแล้ว">ชำระแล้ว</option></select></label><label>เวลาโอนเงิน (ประเทศไทย)<input aria-label="เวลาโอนเงินของออเดอร์" type="datetime-local" value={draft.transferred_at?new Date(new Date(draft.transferred_at).getTime()+7*3600000).toISOString().slice(0,16):''} onChange={e=>patch({transferred_at:e.target.value?new Date(e.target.value+(e.target.value.length===16?':00':'')+'+07:00').toISOString():null})}/></label><p className="admin-field-note">ตรวจยอดรับเงินจริงก่อนเปลี่ยนเป็นชำระแล้ว เวลานี้จะแสดงบนใบเสร็จ</p></section></>}
  {tab==='shipping'&&<section className="admin-detail-section admin-field-grid"><h3><Truck size={20}/>สถานะและข้อมูลจัดส่ง</h3><label>สถานะออเดอร์<select aria-label="สถานะคำสั่งซื้อ" value={draft.status} onChange={e=>patch({status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>บริษัทขนส่ง<select aria-label="บริษัทขนส่ง" value={draft.carrier||''} onChange={e=>patch({carrier:e.target.value})}><option value="">เลือกบริษัทขนส่ง</option>{draft.carrier&&!carriers.includes(draft.carrier)&&<option value={draft.carrier}>{draft.carrier} (ขนส่งเดิม)</option>}{carriers.map(c=><option key={c}>{c}</option>)}</select></label><label className="full">เลขพัสดุ<input aria-label="เลขพัสดุ" value={draft.tracking||''} maxLength={100} onChange={e=>patch({tracking:e.target.value})} placeholder="กรอกเลขที่ได้รับจากขนส่ง"/></label><p className="admin-field-note">เพิ่มรายชื่อขนส่งได้ที่เมนู “ตั้งค่าร้านค้า” · บันทึกแล้วลูกค้าจะเห็นสถานะใหม่</p><a className="admin-outline full" href={'/track?token='+draft.token} target="_blank" rel="noreferrer">เปิดหน้าติดตามของลูกค้า<ExternalLink size={16}/></a></section>}
  {tab==='documents'&&<><section className="admin-detail-section"><OrderDocuments orderId={draft.id} blocked={dirty}/></section><details className="admin-tax-details"><summary><FileText size={18}/>ข้อมูลใบกำกับภาษีผู้ซื้อ</summary><label>ชื่อ / เลขภาษี 13 หลัก / ที่อยู่ (แยกบรรทัด)<textarea aria-label="ข้อมูลใบกำกับภาษีผู้ซื้อ" rows={5} maxLength={1000} value={draft.tax||''} onChange={e=>patch({tax:e.target.value})}/></label><small>แก้ไขแล้วกดบันทึกออเดอร์ก่อนออกใบกำกับภาษี</small></details></>}
  {message&&<p role="status" className="admin-feedback">{message}</p>}
 </div><div className="admin-drawer-save"><span>{dirty?'มีข้อมูลที่ยังไม่บันทึก':<><Check size={16}/>ข้อมูลล่าสุดที่บันทึก</>}</span><button className="admin-primary" disabled={!dirty||busy} onClick={save}><Save size={17}/>{busy?'กำลังบันทึก…':'บันทึกออเดอร์'}</button></div></>}</SheetContent></Sheet>
}
