'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ChevronLeft,ChevronRight,Download,FileText,PackageSearch,Printer,Search,SlidersHorizontal} from 'lucide-react';
import {orderNumber} from '@/lib/order-number';
import {money} from '@/lib/catalog';
import {paymentDate} from '@/lib/payment-view';
import {orderFilters,orderFilterLabels,paymentBadge,orderTone,orderCsv,type AdminOrder,type OrderFilter,type OrderSection} from '@/lib/admin-orders';
type Props={query:string;filter:OrderFilter;date:string;revision:number;compact?:boolean;onFilter:(f:OrderFilter)=>void;onDate:(d:string)=>void;onQuery:(q:string)=>void;onOpen:(o:AdminOrder,section?:OrderSection)=>void;onAll?:()=>void};
export function StatusBadge({order,payment=false}:{order:AdminOrder;payment?:boolean}){const badge=payment?paymentBadge(order):{label:order.status,tone:orderTone(order.status)};return <span className={'admin-badge '+badge.tone}><i/>{badge.label}</span>}
export default function Orders({query,filter,date,revision,compact=false,onFilter,onDate,onQuery,onOpen,onAll}:Props){
 const [rows,setRows]=useState<AdminOrder[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const limit=compact?7:20;
 useEffect(()=>{setPage(1)},[query,filter,date]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>{fetch('/api/admin-orders?'+new URLSearchParams({query,filter,date,page:String(page),limit:String(limit)}),{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.orders);setTotal(d.total)}).catch(e=>{if(e.name!=='AbortError'){setRows([]);setError(e.message)}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})},query?220:0);return()=>{clearTimeout(timer);controller.abort()}},[query,filter,date,page,limit,revision]);
 function download(){const url=URL.createObjectURL(new Blob([orderCsv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='factorboxes-orders-page-'+page+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
 return <section className={'admin-orders-card '+(compact?'compact':'')} aria-busy={loading}>
  <div className="admin-card-heading"><h2><span className="admin-heading-icon"><FileText size={21}/></span>{compact?'คำสั่งซื้อล่าสุด':'รายการคำสั่งซื้อ'}{!compact&&!loading&&<small>{total.toLocaleString()} ออเดอร์</small>}</h2>{compact?<button className="admin-text-button" onClick={onAll}>ดูคำสั่งซื้อทั้งหมด<ArrowRight size={17}/></button>:<button className="admin-outline" disabled={loading||!rows.length} onClick={download}><Download size={16}/>ดาวน์โหลดหน้านี้</button>}</div>
  {!compact&&<><div className="admin-order-filters" role="group" aria-label="กรองสถานะออเดอร์">{orderFilters.map(f=><button type="button" key={f} aria-pressed={filter===f} onClick={()=>onFilter(f)}>{orderFilterLabels[f]}</button>)}</div><div className="admin-table-controls"><label className="admin-inline-search"><Search size={18}/><input aria-label="ค้นหาในรายการออเดอร์" value={query} onChange={e=>onQuery(e.target.value)} placeholder="เลขออเดอร์ ลูกค้า เบอร์โทร หรือเลขพัสดุ"/></label><label className="admin-date-filter"><SlidersHorizontal size={16}/><span>วันที่สั่งซื้อ</span><input type="date" aria-label="กรองวันที่สั่งซื้อ" value={date} onChange={e=>onDate(e.target.value)}/></label>{(query||date)&&<button className="admin-text-button" onClick={()=>{onQuery('');onDate('')}}>ล้างคำค้น / วันที่</button>}</div></>}
  {error?<div role="alert" className="admin-feedback error">{error}</div>:loading?<div className="admin-table-loading" role="status">กำลังโหลดคำสั่งซื้อ…</div>:!rows.length?<div className="admin-empty"><PackageSearch size={40}/><h3>{filter==='all'&&!query&&!date?'ยังไม่มีคำสั่งซื้อ':'ไม่พบออเดอร์ตามเงื่อนไขนี้'}</h3><p>ออเดอร์ใหม่จะปรากฏที่นี่เมื่อมีลูกค้ายืนยันคำสั่งซื้อ</p>{(filter!=='all'||query||date)&&<button className="admin-outline" onClick={()=>{onFilter('all');onQuery('');onDate('')}}>ดูออเดอร์ทั้งหมด</button>}</div>:<>
  <div className="admin-orders-table-wrap"><table className="admin-orders-table"><thead><tr>{['เลขออเดอร์ / วันที่','ลูกค้า','ยอดรวม','สถานะชำระ','สถานะออเดอร์','จัดการ'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><button className="admin-order-number" onClick={()=>onOpen(o)}>{orderNumber(o)}</button><small>{paymentDate(o.created)} น.</small></td><td><strong className="admin-customer-name">{o.customer}</strong><small>{o.phone}</small></td><td><b className="admin-table-money">฿{money(o.total)}</b></td><td><StatusBadge order={o} payment/>{o.pending_slips>0&&o.payment!=='ชำระแล้ว'&&o.status!=='ยกเลิก'&&<button className="admin-slip-shortcut" onClick={()=>onOpen(o,'payment')}>ตรวจสลิป {o.pending_slips} รายการ</button>}</td><td><StatusBadge order={o}/>{o.tracking&&<small className="admin-tracking-small">{o.carrier} · {o.tracking}</small>}</td><td><div className="admin-row-actions"><button className="admin-detail-button" onClick={()=>onOpen(o)}>ดูรายละเอียด</button><button className="admin-print-shortcut" aria-label={'พิมพ์เอกสารออเดอร์ '+orderNumber(o)} onClick={()=>onOpen(o,'documents')}><Printer size={17}/></button></div></td></tr>)}</tbody></table></div>
  <div className="admin-order-mobile-list">{rows.map(o=><article key={o.id}><div><button className="admin-order-number" onClick={()=>onOpen(o)}>{orderNumber(o)}</button><strong>฿{money(o.total)}</strong></div><small>{paymentDate(o.created)} น.</small><h3>{o.customer}</h3><p>{o.phone}</p><div className="admin-mobile-badges"><StatusBadge order={o} payment/><StatusBadge order={o}/></div><div className="admin-mobile-actions"><button className="admin-detail-button" onClick={()=>onOpen(o)}>ดูรายละเอียด<ChevronRight size={15}/></button>{o.pending_slips>0&&o.payment!=='ชำระแล้ว'&&o.status!=='ยกเลิก'&&<button className="admin-text-button" onClick={()=>onOpen(o,'payment')}>ตรวจสลิป</button>}<button className="admin-print-shortcut" aria-label={'พิมพ์เอกสารออเดอร์ '+orderNumber(o)} onClick={()=>onOpen(o,'documents')}><Printer size={17}/></button></div></article>)}</div>
  {!compact&&<div className="admin-pagination"><span>แสดง {(page-1)*limit+1}–{Math.min(page*limit,total)} จาก {total.toLocaleString()} ออเดอร์</span><div><button aria-label="ออเดอร์หน้าก่อน" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>หน้า {page} / {Math.max(1,Math.ceil(total/limit))}</span><button aria-label="ออเดอร์หน้าถัดไป" disabled={page*limit>=total||loading} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div></div>}
  </>}
 </section>
}
