'use client';
import {ArrowRight,BarChart3,ChevronRight,CreditCard,FileCheck2,FileText,Lightbulb,Monitor,Package,Printer,ShoppingCart,Truck,Users,Zap,type LucideIcon} from 'lucide-react';
import {money} from '@/lib/catalog';
import {type AdminAccess,type Permission} from '@/lib/admin-permissions';
import {type AdminOrder,type OrderFilter,type OrderSection} from '@/lib/admin-orders';
import Orders from './orders';
export type Dashboard={date:string;updatedAt:string;orders?:{today:number;yesterday:number;waiting:number;packing:number;shipping:number;delivered:number};slips?:{total:number;orders:number};sales?:{today:number;yesterday:number;month:number;income:number;vat:number;shipping:number};members?:{total:number};bills?:{total:number;amount:number}|null};
type Props={data:Dashboard|null;loading:boolean;error:string;access:AdminAccess;date:string;revision:number;onTab:(tab:string)=>void;onOrders:(filter:OrderFilter,date?:string)=>void;onOpen:(o:AdminOrder,section?:OrderSection)=>void};
function Metric({icon:Icon,label,value,note,tone='orange',onClick}:{icon:LucideIcon;label:string;value:string|number;note:string;tone?:string;onClick:()=>void}){return <button type="button" className={'admin-metric '+tone} onClick={onClick}><span className="admin-metric-icon"><Icon size={24}/></span><span className="admin-metric-content"><span>{label}</span><strong>{value}</strong><small>{note}</small></span></button>}
export default function Overview({data,loading,error,access,date,revision,onTab,onOrders,onOpen}:Props){
 const can=(p:Permission)=>access.owner||access.permissions.includes(p),today=date===new Date(Date.now()+7*3600000).toISOString().slice(0,10),unknown='—';
 const n=(v?:number)=>loading?unknown:v?.toLocaleString()??unknown,baht=(v?:number)=>loading||v===undefined?unknown:'฿'+money(v);
 return <div className="admin-overview">{error&&<p className="admin-feedback error" role="alert">{error}</p>}
  <div className="admin-stat-grid">
   {can('orders')&&<><Metric icon={ShoppingCart} label={today?'ออเดอร์วันนี้':'ออเดอร์วันที่เลือก'} value={n(data?.orders?.today)} note={'วันก่อนหน้า '+n(data?.orders?.yesterday)+' ออเดอร์'} onClick={()=>onOrders('all',date)}/><Metric icon={CreditCard} label="รอชำระเงิน" value={n(data?.orders?.waiting)} note="ยังไม่ยืนยันรับเงิน · ทุกวันที่" onClick={()=>onOrders('waiting')}/><Metric icon={Package} label="รอแพ็ก / กำลังแพ็ก" value={n(data?.orders?.packing)} note="ชำระแล้ว พร้อมเตรียมสินค้า" onClick={()=>onOrders('packing')}/><Metric icon={Truck} label="ระหว่างจัดส่ง" value={n(data?.orders?.shipping)} note="ส่งออกแล้ว รอถึงปลายทาง" tone="blue" onClick={()=>onOrders('shipping')}/></>}
   {can('sales')&&<button className="admin-sales-highlight" onClick={()=>onTab('sales')}><span><BarChart3 size={24}/>{today?'ยอดขายวันนี้':'ยอดขายวันที่เลือก'}</span><strong>{baht(data?.sales?.today)}</strong><small>วันก่อนหน้า {baht(data?.sales?.yesterday)}</small><span className="admin-sales-caption">ชำระแล้ว · ไม่รวมยกเลิก</span></button>}
  </div>
  <div className="admin-dashboard-columns"><div className="admin-dashboard-main">
   <div className="admin-secondary-stats">{can('sales')&&<Metric icon={BarChart3} label={today?'ยอดขายเดือนนี้':'ยอดขายเดือนที่เลือก'} value={baht(data?.sales?.month)} note="รวมยอดออเดอร์ที่ชำระแล้ว" onClick={()=>onTab('sales')}/>} {can('members')&&<Metric icon={Users} label="สมาชิกทั้งหมด" value={n(data?.members?.total)} note="ดูข้อมูลสมาชิกและที่อยู่" onClick={()=>onTab('members')}/>} {can('orders')&&<Metric icon={FileCheck2} label="สลิปที่ต้องตรวจ" value={n(data?.slips?.total)} note={n(data?.slips?.orders)+' ออเดอร์รอตรวจสอบ'} onClick={()=>onOrders('pending')}/>} {can('accounting')&&<Metric icon={FileText} label="บิลครบกำหนด" value={n(data?.bills?.total)} note={data?.bills?'ยอดรอรับ '+baht(data.bills.amount):'เปิดบัญชี / วางบิลเพื่อดูรายละเอียด'} onClick={()=>onTab('accounting')}/>}</div>
   {can('orders')&&<Orders compact query="" filter="all" date="" revision={revision} onFilter={f=>onOrders(f)} onDate={()=>{}} onQuery={()=>{}} onOpen={onOpen} onAll={()=>onOrders('all')}/>}
   {can('sales')&&<section className="admin-vat-strip"><span><b>แยก VAT ของวันที่เลือก</b><small>ออเดอร์ชำระแล้ว · อิงวันที่สั่งซื้อ</small></span><div><small>รายได้สินค้าก่อน VAT</small><strong>{baht(data?.sales?.income)}</strong></div><div><small>VAT ขาย</small><strong>{baht(data?.sales?.vat)}</strong></div><div><small>ค่าจัดส่ง</small><strong>{baht(data?.sales?.shipping)}</strong></div><button className="admin-text-button" onClick={()=>onTab('sales')} aria-label="ดูรายงาน VAT"><ArrowRight size={18}/></button></section>}
  </div><aside className="admin-work-sidebar"><section className="admin-quick-card"><h2><Zap size={21}/>จัดการงานด่วน</h2>{can('orders')&&<><button className="urgent" onClick={()=>onOrders('pending')}><FileCheck2/><span><b>ตรวจสลิปการชำระเงิน</b><small>{n(data?.slips?.total)} สลิปรอตรวจสอบ</small></span><ChevronRight size={17}/></button><button onClick={()=>onOrders('packing')}><Printer className="blue-icon"/><span><b>พิมพ์ใบปะหน้า</b><small>เลือกออเดอร์ที่พร้อมแพ็ก</small></span><ChevronRight size={17}/></button><button onClick={()=>onOrders('paid')}><FileText/><span><b>ใบเสร็จ / ใบกำกับภาษี</b><small>เลือกออเดอร์เพื่อออกเอกสาร</small></span><ChevronRight size={17}/></button></>}
    <a href="/store" target="_blank" rel="noreferrer"><Monitor/><span><b>เปิดหน้าร้าน</b><small>ไปยังเว็บไซต์ของคุณ</small></span><ChevronRight size={17}/></a>
    {can('sales')&&<button onClick={()=>onTab('sales')}><BarChart3 className="green-icon"/><span><b>สรุปยอดขาย / VAT</b><small>รายวัน สัปดาห์ เดือน และปี</small></span><ChevronRight size={17}/></button>}
   </section><section className="admin-tip-card"><h3><Lightbulb size={22}/>เคล็ดลับสำหรับแอดมิน</h3><p>ตรวจยอดรับเงินจริงให้ตรงกับออเดอร์ก่อนยืนยันรับเงิน แล้วจึงแพ็กสินค้าและพิมพ์ใบปะหน้า</p><span className="admin-tip-line"/></section></aside></div>
 </div>
}
