'use client';
import {useEffect,useState} from 'react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Choice} from '../shared';
import {money} from '@/lib/catalog';
const periods={'รายวัน':'day','รายสัปดาห์':'week','รายเดือน':'month','รายปี':'year'};
export default function Sales(){const [period,setPeriod]=useState('รายวัน'),[date,setDate]=useState(()=>new Date(Date.now()+7*3600000).toISOString().slice(0,10)),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setData(null);fetch('/api/sales?'+new URLSearchParams({period:periods[period as keyof typeof periods],date}),{signal:controller.signal}).then(async r=>{const d=await r.json() as any;if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return ()=>controller.abort()},[period,date,revision]);
const thai=(s:string)=>new Date(s+'T00:00:00+07:00').toLocaleDateString('th-TH',{timeZone:'Asia/Bangkok',day:'numeric',month:'short',year:'numeric'});
function bucket(s:string){if(period==='รายวัน')return s.slice(11)+' น.';if(period==='รายปี')return new Date(s+'-01T00:00:00+07:00').toLocaleDateString('th-TH',{timeZone:'Asia/Bangkok',month:'long',year:'numeric'});return thai(s)}
return <section className="panel"><div className="sectionhead"><div><h2>สรุปยอดขาย</h2><p className="muted">ออเดอร์ชำระแล้ว ไม่รวมออเดอร์ยกเลิก · นับตามวันที่สั่งซื้อ</p></div><button className="secondary" disabled={loading} onClick={()=>setRevision(v=>v+1)}>รีเฟรชยอดขาย</button></div><div className="reportcontrols"><label>ช่วงเวลา<Choice label="ช่วงสรุปยอดขาย" value={period} items={Object.keys(periods)} onChange={setPeriod}/></label><label>เลือกวันที่ในช่วงที่ต้องการ<input type="date" required value={date} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label></div><p className="muted">เวลาประเทศไทย · สัปดาห์เริ่มวันจันทร์ถึงวันอาทิตย์</p>{loading?<p role="status">กำลังคำนวณยอดขาย…</p>:error?<p className="error" role="alert">{error}</p>:data&&<><h3>{thai(data.range.from)}{data.range.from!==data.range.through?' – '+thai(data.range.through):''}</h3><div className="salesstats salesvatstats">{[['รายได้จากสินค้า (ไม่รวม VAT)',money(data.totals.goods-data.totals.vat)+' บาท'],['VAT ขายที่รวมในสินค้า',money(data.totals.vat)+' บาท'],['ยอดสินค้า (รวม VAT)',money(data.totals.goods)+' บาท'],['ค่าจัดส่ง',money(data.totals.shipping)+' บาท'],['ยอดรวมที่ลูกค้าชำระ',money(data.totals.total)+' บาท'],['ออเดอร์ชำระแล้ว',data.totals.orders.toLocaleString()+' ออเดอร์']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="muted">ยอดสินค้าหักส่วนลดตามเรทและ CODE แล้ว รายได้ไม่รวม VAT ยังไม่ได้หักต้นทุนและค่าใช้จ่าย จึงไม่ใช่กำไรสุทธิ</p><div className="notice"><b>แยก VAT ออกจากราคาที่รวมภาษีแล้ว</b><p>ตัวอย่าง VAT 7%: ยอดสินค้า 1,070 บาท = รายได้จากสินค้า 1,000 บาท + VAT 70 บาท</p><p>รายงานใช้ยอด VAT ที่บันทึกจริงในแต่ละออเดอร์ ค่าส่งแสดงแยกตามระบบร้าน และ VAT ขายนี้ยังไม่หักภาษีซื้อ</p></div>{!data.rows.length?<div className="empty">ยังไม่มีออเดอร์ที่ชำระแล้วในช่วงนี้</div>:<Table><TableHeader><TableRow>{['ช่วงเวลา','ออเดอร์','รายได้สินค้าไม่รวม VAT','VAT ขาย','ยอดสินค้ารวม VAT','ค่าส่ง','ยอดรวมที่ลูกค้าชำระ'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{data.rows.map((r:any)=><TableRow key={r.bucket}><TableCell>{bucket(r.bucket)}</TableCell><TableCell>{r.orders}</TableCell><TableCell><b>฿{money(r.goods-r.vat)}</b></TableCell><TableCell>฿{money(r.vat)}</TableCell><TableCell>฿{money(r.goods)}</TableCell><TableCell>฿{money(r.shipping)}</TableCell><TableCell><b>฿{money(r.total)}</b></TableCell></TableRow>)}</TableBody></Table>}</>}</section>}
