'use client';
import {useEffect,useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {permissionKeys,permissionLabels,type Permission} from '@/lib/admin-permissions';
export default function Staff(){const [staff,setStaff]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[search,setSearch]=useState(''),[selected,setSelected]=useState<any>(null),[permissions,setPermissions]=useState<Permission[]>([]),[active,setActive]=useState(true),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
async function load(q=''){setLoading(true);try{const r=await fetch('/api/admin-users?q='+encodeURIComponent(q));const d=await r.json() as any;if(!r.ok)throw Error(d.error);setStaff(d.staff);setMembers(d.members)}catch(e){setMessage((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
function edit(m:any){const s=staff.find(s=>s.member_id===(m.id||m.member_id));setSelected({id:m.id||m.member_id,name:m.name,email:m.email});setPermissions(s?.permissions||[]);setActive(s?s.active===1:true);setMessage('')}
async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/admin-users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberId:selected.id,permissions,active})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);await load(search);setSelected(null);setMessage('บันทึกสิทธิ์แล้ว มีผลกับการเปิดหน้าและการทำรายการครั้งถัดไป')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
return <section className="panel"><h2>แอดมินและสิทธิ์</h2><div className="notice"><b>เจ้าของร้านมีสิทธิ์ครบทุกส่วน</b><p>เฉพาะเจ้าของร้านเพิ่มผู้ดูแล เปลี่ยนสิทธิ์ หรือปิดการเข้าหลังบ้านได้</p><p>ผู้ดูแลใช้อีเมลและรหัสผ่าน ของตนเอง ไม่ใช้รหัสผ่านร่วมกัน ให้ผู้ดูแลลงทะเบียนที่หน้าสมาชิกก่อน แล้วเลือกบัญชีด้านล่าง</p><p>ผู้ดูแลต้องยืนยันอีเมลและบันทึกข้อมูลที่หน้าสมาชิกก่อน จึงจะปรากฏให้เลือก</p></div>{message&&<p role="status" className="notice">{message}</p>}<h3>ผู้ดูแลที่กำหนดไว้</h3>{loading?<p>กำลังโหลด…</p>:!staff.length?<p className="muted">ยังไม่มีผู้ดูแลเพิ่มเติม</p>:<div className="stafflist">{staff.map(s=><div className="staffrow" key={s.member_id}><div><b>{s.name}</b><small>{s.email} · {s.active?'เปิดใช้งาน':'ปิดสิทธิ์แล้ว'}</small><p>{s.permissions.map((p:Permission)=>permissionLabels[p]).join(' · ')}</p></div><button className="secondary" onClick={()=>edit(s)}>แก้ไขสิทธิ์</button></div>)}</div>}<h3>เพิ่มผู้ดูแลจากสมาชิก</h3><form className="reportcontrols" onSubmit={e=>{e.preventDefault();load(search)}}><label>ค้นหาชื่อหรืออีเมลติดต่อ<input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="ชื่อหรืออีเมลสมาชิก"/></label><button className="secondary" disabled={loading}>ค้นหา</button></form><small className="muted">แสดงสมาชิกไม่เกิน 50 รายการ ใช้การค้นหาเพื่อค้นบัญชีที่ต้องการ</small><div className="stafflist">{members.map(m=><div className="staffrow" key={m.id}><div><b>{m.name}</b><small>{m.email}</small></div><button className="secondary" onClick={()=>edit(m)}>เลือกบัญชี</button></div>)}</div>{!loading&&!members.length&&<p className="muted">ไม่พบสมาชิก ให้ผู้ดูแลลงทะเบียนก่อน หรือเปลี่ยนคำค้นหา</p>}{selected&&<div className="staffeditor form"><h3>สิทธิ์ของ {selected.name}</h3><p>{selected.email}</p><p className="muted">ตรวจสอบบัญชีให้ตรงกับผู้ดูแลก่อนบันทึก อีเมลนี้เป็นข้อมูลติดต่อของสมาชิก</p>{permissionKeys.map(p=><label key={p} className="checkline"><Checkbox checked={permissions.includes(p)} onCheckedChange={v=>setPermissions(old=>v===true?[...old.filter(k=>k!==p),p]:old.filter(k=>k!==p))}/>{permissionLabels[p]}</label>)}<label className="checkline"><Checkbox checked={active} onCheckedChange={v=>setActive(v===true)}/>อนุญาตให้เข้าหลังบ้าน</label><div className="reviewactions"><button className="primary" disabled={busy||(active&&!permissions.length)} onClick={save}>{busy?'กำลังบันทึก…':'บันทึกสิทธิ์'}</button><button className="secondary" disabled={busy} onClick={()=>setSelected(null)}>ยกเลิก</button></div></div>}</section>}
