'use client';
import {useCallback,useEffect,useState} from 'react';
import {Bell,Check,ChevronLeft,RefreshCw,Smartphone} from 'lucide-react';
import {usePwa} from '../pwa';
type Preferences={orders:boolean;marketing:boolean;cart_reminders:boolean;reorder_reminders:boolean};
type Message={id:string;kind:string;title:string;body:string;url:string;created_at:string;read_at:string|null};
const defaults:Preferences={orders:true,marketing:false,cart_reminders:false,reorder_reminders:false};
export default function Screen(){
 const {installed}=usePwa();const [data,setData]=useState<{messages:Message[];counts:{total:number;unread:number};publicKey:string|null;configured:boolean}|null>(null),[preferences,setPreferences]=useState(defaults),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[login,setLogin]=useState(false),[supported,setSupported]=useState(false),[ios,setIos]=useState(false),[subscribed,setSubscribed]=useState(false),[selected,setSelected]=useState<Message|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/notifications?page='+page,{cache:'no-store'});if(r.status===401){setLogin(true);setData(null);return}const d=await r.json();if(!r.ok)throw Error(d.error);setLogin(false);setData(d);setPreferences(d.preferences)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[page]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('id');if(!id)return;let active=true;fetch('/api/notifications?id='+encodeURIComponent(id),{cache:'no-store'}).then(async r=>{if(!r.ok)return;const d=await r.json();if(active)setSelected(d.notification)}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{setIos(/iPhone|iPad|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1));setSupported(isSecureContext&&'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window);if('serviceWorker' in navigator){navigator.serviceWorker.getRegistration('/').then(r=>r?.pushManager.getSubscription()).then(s=>setSubscribed(Boolean(s))).catch(()=>{});const update=()=>void load();navigator.serviceWorker.addEventListener('message',update);return()=>navigator.serviceWorker.removeEventListener('message',update)}},[load]);
 async function post(body:unknown){const r=await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d}
 async function save(){setBusy(true);setNotice('');try{await post({action:'preferences',preferences});setNotice('บันทึกการตั้งค่าแล้ว');window.dispatchEvent(new Event('notification-preferences-updated'));await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function enable(){
  if(!data?.publicKey||!supported||busy)return;setBusy(true);setError('');setNotice('');
  try{
   // The permission request must happen directly in the click handler on iOS.
   const permission=await Notification.requestPermission();if(permission!=='granted'){setNotice('ยังไม่ได้รับอนุญาต หากเคยปิดไว้ ให้เปิดสิทธิ์แจ้งเตือนในการตั้งค่ามือถือ/เบราว์เซอร์');return}
   await navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'});
   const reg=await Promise.race([navigator.serviceWorker.ready,new Promise<never>((_,reject)=>setTimeout(()=>reject(Error('เตรียมระบบไม่สำเร็จ กรุณารีเฟรชแล้วลองใหม่')),15000))]);
   const raw=atob(data.publicKey.replace(/-/g,'+').replace(/_/g,'/'));const key=Uint8Array.from(raw,c=>c.charCodeAt(0));
   let sub=await reg.pushManager.getSubscription();if(sub&&String(new Uint8Array(sub.options.applicationServerKey||new ArrayBuffer(0)))!==String(key)){await sub.unsubscribe();sub=null}
   sub=sub||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});
   await post({action:'subscribe',subscription:sub.toJSON()});setSubscribed(true);setNotice('เชื่อมต่อเครื่องนี้แล้ว เลือกประเภทข้อความและกดบันทึกได้เลย');
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 async function disable(){setBusy(true);try{const r=await navigator.serviceWorker.getRegistration('/'),s=await r?.pushManager.getSubscription();if(s){await post({action:'unsubscribe',endpoint:s.endpoint});await s.unsubscribe()}setSubscribed(false);setNotice('ปิดแจ้งเตือนบนเครื่องนี้แล้ว')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function read(m?:Message){try{await post({action:'read',id:m?.id});window.dispatchEvent(new Event('notification-read'));if(m)location.assign(m.url);else await load()}catch(e){setError((e as Error).message)}}
 return <main className="fb-notifications"><a className="notification-back" href="/"><ChevronLeft size={18}/>หน้าแรก</a><div className="notification-heading"><div><span>FACTORBOXES / NOTIFICATIONS</span><h1>ทุกอัปเดต อยู่ตรงนี้</h1><p>ติดตามออเดอร์ และเลือกข่าวสารที่คุณอยากรับ</p></div><Bell size={35}/></div>
 {login?<section className="notification-card"><h2>เข้าสู่ระบบเพื่อดูข้อความของคุณ</h2><p>ระบบจะแสดงเฉพาะออเดอร์ที่ผูกกับบัญชีนี้</p><a className="notification-primary" href="/login?next=%2Fnotifications">เข้าสู่ระบบ / สมัครสมาชิก</a></section>:<>
 {error&&<div role="alert" className="notification-error">{error}<button onClick={load}>ลองใหม่</button></div>}
 <section className="notification-card"><h2><Smartphone/>แจ้งเตือนบนหน้าจอมือถือ</h2><p>รับความคืบหน้าได้แม้ไม่ได้เปิดหน้าเว็บ</p>{ios&&!installed?<div className="notification-hint">สำหรับ iPhone / iPad ให้เพิ่มแอปลงหน้าจอโฮม แล้วเปิดผ่านไอคอนก่อน<a href="/install">ดูวิธีติดตั้งแอป →</a></div>:!supported?<p className="notification-hint">เบราว์เซอร์นี้ยังไม่พร้อมรับ Push คุณยังอ่านประวัติข้อความด้านล่างได้</p>:<div className="notification-buttons"><button className="notification-primary" onClick={enable} disabled={busy||!data?.configured}><Bell size={18}/>{subscribed?'เชื่อมต่อแจ้งเตือนเครื่องนี้อีกครั้ง':'เปิดรับแจ้งเตือนบนเครื่องนี้'}</button>{subscribed&&<button onClick={disable} disabled={busy}>ปิดบนเครื่องนี้</button>}</div>}{data&&!data.configured&&<p className="notification-hint">ขณะนี้อ่านแจ้งเตือนในแอปได้ การส่งขึ้นหน้าจอมือถือจะพร้อมเมื่อร้านเปิดระบบ</p>}{subscribed&&<p className="notification-connected"><Check size={16}/>เบราว์เซอร์มีการสมัครรับ Push แล้ว</p>}
 <details className="notification-settings"><summary>ตั้งค่าประเภทข้อความที่ต้องการรับ</summary><div className="notification-preferences">{([['orders','สถานะคำสั่งซื้อ','รับออเดอร์ · ยืนยันชำระเงิน · แพ็ค · เลขพัสดุ'],['marketing','โค้ดส่วนลดและโปรโมชั่น','ข่าวสารและข้อเสนอจาก FACTORBOXES'],['cart_reminders','เตือนสินค้าที่ค้างในตะกร้า','สำหรับตะกร้าที่บันทึกขณะเข้าสู่ระบบ'],['reorder_reminders','เตือนกลับมาสั่งซื้อ','เมื่อถึงเวลาเติมสต็อกกล่อง']] as const).map(([key,label,hint])=><label key={key}><span><b>{label}</b><small>{hint}</small></span><input type="checkbox" checked={preferences[key]} disabled={busy||!data||((key==='cart_reminders'||key==='reorder_reminders')&&!preferences.marketing)} onChange={e=>setPreferences(p=>({...p,[key]:e.target.checked,...(key==='marketing'&&!e.target.checked?{cart_reminders:false,reorder_reminders:false}:{})}))}/></label>)}</div><p className="notification-small">ข้อความชวนซื้อส่งช่วง 09:00–20:00 น. ไม่เกิน 1 ข้อความต่อวัน คุณปิดรับได้ทุกเมื่อ</p><div className="notification-buttons"><button className="notification-primary" onClick={save} disabled={busy||!data}>บันทึกการตั้งค่า</button>{subscribed&&<button disabled={busy||!preferences.orders} onClick={async()=>{setBusy(true);try{await post({action:'test'});setNotice('เพิ่มข้อความทดสอบเข้าคิวแล้ว');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>ทดสอบแจ้งเตือนของฉัน</button>}</div></details>{notice&&<p role="status" className="notification-connected">{notice}</p>}</section>
 {selected&&<section className="notification-card notification-selected"><small>ข้อความที่คุณเปิด</small><h2>{selected.title}</h2><p>{selected.body}</p><button className="notification-primary" onClick={()=>read(selected)}>ดูรายละเอียด →</button></section>}
 <section className="notification-card"><div className="notification-list-heading"><h2><Bell/>ข้อความของคุณ <small>{data?.counts.unread||0} ยังไม่อ่าน</small></h2><button aria-label="รีเฟรชแจ้งเตือน" onClick={load}><RefreshCw size={18}/></button></div>{!!data?.counts.unread&&<button className="notification-readall" onClick={()=>read()}>ทำเครื่องหมายว่าอ่านทั้งหมด</button>}{loading?<p role="status">กำลังโหลดข้อความ…</p>:data?.messages.length?data.messages.map(m=><button className={'notification-message '+(!m.read_at?'is-unread':'')} key={m.id} onClick={()=>read(m)}><span><b>{m.title}</b><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</small></span><span aria-label={m.read_at?'อ่านแล้ว':'ยังไม่อ่าน'}>{m.read_at?'':'●'} →</span></button>):<p className="notification-empty">ยังไม่มีข้อความใหม่<br/>สถานะออเดอร์ครั้งถัดไปจะแสดงที่นี่</p>}{!!data&&data.counts.total>25&&<div className="notification-buttons"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>ก่อนหน้า</button><span>หน้า {page}</span><button disabled={page*25>=data.counts.total} onClick={()=>setPage(p=>p+1)}>ถัดไป</button></div>}</section></>}
 <a className="notification-back" href="/store">เลือกซื้อกล่อง →</a></main>
}
