const {PGlite}=require('@electric-sql/pglite');const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict');
(async()=>{const pg=new PGlite();await pg.exec('CREATE ROLE anon;CREATE ROLE authenticated;');for(const f of ['01-schema.sql','04-order-numbers.sql','06-accounting.sql','06-accounting.sql'])await pg.exec(fs.readFileSync('supabase/'+f,'utf8'));
let permissions=['accounting'];const database={prepare(sql){return {bind(...v){this.v=v;return this},async exec(){let i=0;return pg.query(sql.replaceAll('?',()=>'$'+(++i)),this.v||[])},async first(){return (await this.exec()).rows[0]||null},async all(){return {results:(await this.exec()).rows}},async run(){return this.exec()}}},async batch(statements){await pg.exec('BEGIN');try{const rows=[];for(const q of statements){const r=await q.exec();rows.push({...r,rowCount:r.affectedRows})}await pg.exec('COMMIT');return rows}catch(e){await pg.exec('ROLLBACK');throw e}}};const server={db:()=>database,isAdmin:async p=>permissions.includes(p)};const modules={'zod':require('zod'),'./server':server,'@/lib/server':server,'@/lib/member':{identity:async()=>({email:'accountant@example.test'})}};
function load(file){const exports={};new Function('exports','require',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(exports,k=>{if(!(k in modules))throw Error(k);return modules[k]});return exports}
modules['./accounting']=modules['@/lib/accounting']=load('lib/accounting.ts');modules['@/lib/sales']=load('lib/sales.ts');modules['@/lib/accounting-server']=load('lib/accounting-server.ts');const api=load('app/api/accounting/route.ts'),{thaiToday,csv,escapeHtml}=modules['./accounting'];const today=thaiToday(),order='11111111-1111-4111-8111-111111111111',entry='22222222-2222-4222-8222-222222222222',payment='33333333-3333-4333-8333-333333333333';
const req=(body,origin='https://shop.test')=>new Request('https://shop.test/api/accounting',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const post=(body,origin)=>api.POST(req(body,origin));
await pg.query("INSERT INTO orders(id,token,created,customer,phone,address,tax,items,subtotal,shipping,vat,total,status,carrier,tracking,payment) VALUES($1,$1,$2,'Customer','0','Address','','[]',10700,0,700,10700,'รอยืนยัน','','','รอชำระ')",[order,new Date().toISOString()]);await pg.query("INSERT INTO settings(id,value) VALUES('shop',$1)",[JSON.stringify({seller:'Test Co',sellerAddress:'Address',sellerTax:'1234567890123'})]);
permissions=[];assert.equal((await api.GET(new Request('https://shop.test/api/accounting'))).status,403);assert.equal((await post({action:'sync'})).status,403);permissions=['accounting'];assert.equal((await post({action:'sync'},'https://other.test')).status,403);
assert.equal((await post({action:'terms',order,due_date:today,assignee:'staff',note:'30 days'})).status,200);assert.equal((await pg.query('SELECT * FROM accounting_bills')).rows.length,1);await post({action:'sync'});assert.equal((await pg.query('SELECT * FROM accounting_bills')).rows.length,1);const snapshot=JSON.stringify((await pg.query('SELECT payload FROM accounting_bills')).rows[0].payload);await pg.query("UPDATE orders SET customer='Changed' WHERE id=$1",[order]);await post({action:'sync'});assert.equal(JSON.stringify((await pg.query('SELECT payload FROM accounting_bills')).rows[0].payload),snapshot);
assert.equal((await post({action:'terms',order,due_date:'2099-01-01',assignee:'',note:''})).status,200);assert.ok((await pg.query('SELECT voided_at FROM accounting_bills')).rows[0].voided_at);assert.equal((await post({action:'terms',order,due_date:today,assignee:'',note:''})).status,200);assert.equal((await pg.query('SELECT * FROM accounting_bills WHERE voided_at IS NULL')).rows.length,1);
const data={action:'entry',id:entry,kind:'expense',document_date:today,due_date:today,counterparty:'Supplier',reference:'INV1',category:'packing',description:'Purchase',amount:10700,vat:700,assignee:'staff'};assert.equal((await post(data)).status,200);
const paid_at=new Date(Date.now()-60000).toISOString();const pay={action:'payment',id:payment,entry,amount:4000,paid_at,reference:'BANK1'};assert.equal((await post(pay)).status,200);assert.equal((await post(pay)).status,200);assert.equal((await pg.query('SELECT * FROM accounting_payments')).rows.length,1);
const oldError=console.error;console.error=()=>{};try{assert.equal((await post({...pay,amount:5000})).status,400);assert.equal((await post({...pay,id:crypto.randomUUID(),amount:10000})).status,400)}finally{console.error=oldError}
const res=await api.GET(new Request('https://shop.test/api/accounting?view=entries'));const body=await res.json();assert.equal(Number(body.rows[0].balance),6700);assert.equal((await post({action:'void-entry',id:entry,reason:'mistake'})).status,409);assert.equal((await post({action:'void-payment',id:payment,reason:'duplicate'})).status,200);assert.equal((await post({action:'void-entry',id:entry,reason:'mistake'})).status,200);
assert.equal((await post({action:'order-payment',order,paid_at})).status,200);const summary=await (await api.GET(new Request('https://shop.test/api/accounting?date='+today))).json();assert.equal(Number(summary.ar.amount),0);assert.equal(Number(summary.cash.amount),10700);
assert.ok(csv([['=HYPERLINK("x")']]).includes("'=HYPERLINK"));assert.equal(escapeHtml('<script>'), '&lt;script&gt;');
modules['./order-number']=load('lib/order-number.ts');modules['./accounting']=modules['@/lib/accounting'];const {documentHTML}=load('lib/accounting-documents.ts');const html=documentHTML((await pg.query('SELECT *,due_date::text AS due_date FROM accounting_bills WHERE voided_at IS NULL')).rows[0],true);assert.ok(html.includes('ใบวางบิล'));assert.ok(html.includes('Test Co'));
const {zipFiles}=load('lib/zip.ts');fs.writeFileSync('/tmp/accounting-export-test.zip',zipFiles([{name:'document.html',data:Buffer.from(html)},{name:'test.csv',data:Buffer.from(csv([['ไทย',107]]))}]));
modules['@/lib/order-number']=modules['./order-number'];modules['@/lib/accounting-documents']={documentHTML};modules['@/lib/zip']={zipFiles};modules['@/lib/storage']={storageBucket:{get:async()=>null}};const exporter=load('app/api/accounting/export/route.ts');const exportRequest=new Request('https://shop.test/api/accounting/export?from='+today+'&through='+today);const bundle=await exporter.GET(exportRequest);assert.equal(bundle.status,200,bundle.ok?'':await bundle.clone().text());assert.equal(bundle.headers.get('content-type'),'application/zip');fs.writeFileSync('/tmp/accounting-route-export.zip',Buffer.from(await bundle.arrayBuffer()));permissions=[];assert.equal((await exporter.GET(exportRequest)).status,403);permissions=['accounting'];assert.equal((await post({action:'order-payment',order,paid_at})).status,200);assert.equal((await post({action:'order-payment',order,paid_at:new Date(Date.now()-120000).toISOString()})).status,409);
const concurrent=crypto.randomUUID();await post({...data,id:concurrent,reference:'INV-CONCURRENT'});const a=crypto.randomUUID(),b=crypto.randomUUID();const attempts=await Promise.allSettled([pg.query('SELECT accounting_pay($1,$2,8000,$3,$4,$5)',[a,concurrent,paid_at,'A','test']),pg.query('SELECT accounting_pay($1,$2,8000,$3,$4,$5)',[b,concurrent,paid_at,'B','test'])]);assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);assert.equal(Number((await pg.query('SELECT sum(amount) AS n FROM accounting_payments WHERE entry_id=$1',[concurrent])).rows[0].n),8000);
await pg.exec('SET ROLE anon');await assert.rejects(()=>pg.query('SELECT * FROM accounting_entries'));await assert.rejects(()=>pg.query('SELECT accounting_pay($1,$2,1,now(),$3,$4)',[crypto.randomUUID(),entry,'','']));await pg.close();console.log('PASS accounting migration, roles, billing dedup/snapshots/rescheduling, partial payments/idempotency/overpayment, void history, order reconciliation, CSV escaping, HTML, ZIP.');})().catch(e=>{console.error(e);process.exit(1)});
