const {PGlite}=require('@electric-sql/pglite');const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict');
(async()=>{const pg=new PGlite();await pg.exec('CREATE ROLE anon;CREATE ROLE authenticated;');await pg.exec(fs.readFileSync('supabase/01-schema.sql','utf8'));let allowed=['orders','settings'];
const database={prepare(sql){return {bind(...values){this.values=values;return this},async exec(){let i=0;return pg.query(sql.replaceAll('?',()=>'$'+(++i)),this.values||[])},async first(){return (await this.exec()).rows[0]||null},async run(){return this.exec()}}}};
const server={db:()=>database,isAdmin:async p=>p?allowed.includes(p):allowed.length>0};
const modules={'zod':require('zod'),'./server':server,'@/lib/server':server,'@/lib/member':{},'@/lib/coupons':{},'@/lib/catalog':{statuses:['รอยืนยัน','จัดส่งแล้ว','ส่งสำเร็จ'],categories:['กล่อง','อุปกรณ์แพ็ค','สินค้าอื่น ๆ']}};
function load(path){const exports={};new Function('exports','require',ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(exports,k=>{if(!(k in modules))throw Error(k);return modules[k]});return exports}
modules['./carriers']=modules['@/lib/carriers']=load('lib/carriers.ts');modules['@/lib/carriers-server']=load('lib/carriers-server.ts');const {getCarriers}=modules['@/lib/carriers-server'];const route=load('app/api/shop/route.ts');
const request=(body,origin='https://shop.test')=>new Request('https://shop.test/api/shop',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
assert.ok((await getCarriers()).includes('Flash Express'));allowed=['orders'];assert.equal((await route.POST(request({action:'carriers',carriers:['รถร้าน']}))).status,403);allowed=['orders','settings'];assert.equal((await route.POST(request({action:'carriers',carriers:['รถร้าน']},'https://other.test'))).status,403);
const err=console.error;console.error=()=>{};try{for(const names of [[''],['Flash',' flash '],['x'.repeat(81)]])assert.equal((await route.POST(request({action:'carriers',carriers:names}))).status,400)}finally{console.error=err}
assert.equal((await route.POST(request({action:'carriers',carriers:[' รถร้าน ','Flash']}))).status,200);assert.deepEqual(await getCarriers(),['รถร้าน','Flash']);
const id='11111111-1111-4111-8111-111111111111';await pg.query("INSERT INTO orders(id,token,created,customer,phone,address,tax,items,subtotal,shipping,vat,total,status,carrier,tracking,payment) VALUES ($1,$1,'2026-09-07','Test','0','address','','[]',100,0,0,100,'รอยืนยัน','ขนส่งเก่า','','รอชำระ')",[id]);const order={action:'update',id,status:'จัดส่งแล้ว',payment:'รอชำระ',carrier:'ขนส่งเก่า',tracking:'TRACK01'};
assert.equal((await route.POST(request(order))).status,200);assert.equal((await route.POST(request({...order,carrier:'ไม่ได้เพิ่ม'}))).status,400);assert.equal((await route.POST(request({...order,carrier:'รถร้าน'}))).status,200);
assert.equal((await route.POST(request({action:'carriers',carriers:[]}))).status,200);assert.deepEqual(await getCarriers(),[]);assert.equal((await route.POST(request({...order,carrier:'รถร้าน'}))).status,200);assert.equal((await pg.query('SELECT carrier FROM orders WHERE id=$1',[id])).rows[0].carrier,'รถร้าน');await pg.close();console.log('PASS carrier persistence, defaults, permissions, origin, validation, selection, removed carrier history, empty list.');})().catch(e=>{console.error(e);process.exit(1)});
