const {PGlite}=require('@electric-sql/pglite');const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict');
(async()=>{const pg=new PGlite();await pg.exec('CREATE ROLE anon; CREATE ROLE authenticated;');await pg.exec(fs.readFileSync('supabase/01-schema.sql','utf8'));await pg.exec(fs.readFileSync('supabase/04-order-numbers.sql','utf8'));let owner=true,fail=false,removed=[];
function prepare(sql){return {values:[],bind(...v){this.values=v;return this},async exec(){if(fail&&sql.startsWith('DELETE FROM orders'))throw Error('simulated failure');let n=0;return pg.query(sql.replaceAll('?',()=>'$'+(++n)),this.values)},async first(){return (await this.exec()).rows[0]||null},async all(){return {results:(await this.exec()).rows}}}}
const db={prepare,async batch(qs){await pg.exec('BEGIN');try{for(const q of qs)await q.exec();await pg.exec('COMMIT')}catch(e){await pg.exec('ROLLBACK');throw e}}};
const route={};new Function('exports','require',ts.transpileModule(fs.readFileSync('app/api/delete-order/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(route,k=>({'@/lib/order-number':{orderNumber:o=>String(o.order_no).padStart(4,'0')},'zod':require('zod'),'@/lib/server':{db:()=>db,adminAccess:async()=>({owner})},'@/lib/storage':{storageBucket:{delete:async key=>removed.push(key)}}}[k]));
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
for(const o of [id,other])await pg.query("INSERT INTO orders(id,token,created,customer,phone,address,tax,items,subtotal,shipping,vat,total,status,carrier,tracking,payment) VALUES ($1,$1,'2026-09-06T00:00:00.000Z','Test','0','address','','[]',107000,0,7000,107000,'ส่งสำเร็จ','','','ชำระแล้ว')",[o]);
await pg.query("INSERT INTO slips(id,order_id,storage_key,mime,created,status,note) VALUES ('slip',$1,'test-slip','image/png','2026-09-06','อนุมัติ','')",[id]);await pg.query("INSERT INTO documents(order_id,type,created,payload) VALUES ($1,'receipt','2026-09-06','{}')",[id]);
const request=(confirmation='0000',origin='https://shop.test')=>new Request('https://shop.test/api/delete-order',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify({id,confirmation})});
owner=false;assert.equal((await route.POST(request())).status,403);owner=true;assert.equal((await route.POST(request('wrong'))).status,400);assert.equal((await route.POST(request('0000','https://attacker.test'))).status,403);
fail=true;const original=console.error;console.error=()=>{};assert.equal((await route.POST(request())).status,400);console.error=original;assert.equal((await pg.query('SELECT count(*)::int n FROM slips')).rows[0].n,1);assert.equal((await pg.query('SELECT count(*)::int n FROM documents')).rows[0].n,1);assert.equal(removed.length,0);
fail=false;assert.equal((await route.POST(request())).status,200);assert.equal((await pg.query('SELECT count(*)::int n FROM orders')).rows[0].n,1);assert.equal((await pg.query('SELECT count(*)::int n FROM slips')).rows[0].n,0);assert.equal((await pg.query('SELECT count(*)::int n FROM documents')).rows[0].n,0);const totals=(await pg.query('SELECT sum(subtotal)::int goods,sum(vat)::int vat FROM orders')).rows[0];assert.deepEqual(totals,{goods:107000,vat:7000});assert.deepEqual(removed,['test-slip']);assert.equal((await route.POST(request())).status,404);await pg.close();console.log('PASS owner-only, origin, confirmation, transactional rollback, dependent deletion, storage cleanup, unrelated order preserved, sales and VAT reduced.');})().catch(e=>{console.error(e);process.exit(1)});
