const {PGlite}=require('@electric-sql/pglite'),fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict');
(async()=>{
 const pg=new PGlite();await pg.exec('CREATE ROLE anon;CREATE ROLE authenticated;');for(const f of ['01-schema.sql','04-order-numbers.sql'])await pg.exec(fs.readFileSync('supabase/'+f,'utf8'));
 let user=null,calls=0;const adapter={prepare(sql){calls++;return {bind(...v){this.v=v;return this},async exec(){let n=0;return pg.query(sql.replaceAll('?',()=>'$'+(++n)),this.v||[])},async first(){return (await this.exec()).rows[0]||null},async all(){return {results:(await this.exec()).rows}},async run(){return {meta:{changes:(await this.exec()).affectedRows}}}}}};
 const modules={'zod':require('zod'),'@/lib/member':{identity:async()=>user},'@/lib/server':{db:()=>adapter}};
 function load(path){const e={};new Function('exports','require',ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(e,k=>modules[k]);return e}
 const view=modules['@/lib/member-orders']=load('lib/member-orders.ts');const api=load('app/api/member-orders/route.ts');
 const req=q=>new Request('https://shop.test/api/member-orders?'+new URLSearchParams(q));
 const post=(token,origin='https://shop.test')=>new Request('https://shop.test/api/member-orders',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify({token})});
 async function add(member,status='ส่งสำเร็จ',payment='ชำระแล้ว',items=null){const id=crypto.randomUUID(),token=crypto.randomUUID();const snapshot=JSON.stringify(items||[{id:'SX',sku:'001',name:'กล่องเดิม 100% แพ็ค',category:'กล่อง',size:'8.2 × 12.5 × 4.5',qty:100,price:82},{id:'AB',sku:'010',name:'กล่อง AB',qty:200,price:236}]);await pg.query("INSERT INTO orders(id,token,created,customer,phone,address,tax,items,subtotal,shipping,vat,total,status,carrier,tracking,payment,member_id,coupon_code,coupon_discount,transferred_at) VALUES($1,$2,'2026-09-01T10:00:00.000Z','ชื่อที่บันทึกตอนสั่ง','0800000000','ที่อยู่ตอนสั่ง ไม่ใช่ที่อยู่สมาชิกปัจจุบัน','ข้อมูลผู้ซื้อเดิม',$3,54400,10000,3559,64400,$4,'J&T Express',$5,$6,$7,'SAVE10',1000,'2026-09-01T11:00:00Z')",[id,token,snapshot,status,'TH-'+id,payment,member]);return {id,token,snapshot}}
 const mine=await add('alice'),other=await add('bob'),guest=await add(null);
 const waiting=await add('alice','รอชำระเงิน','รอชำระ'),cancelled=await add('alice','ยกเลิก','รอชำระ');
 await pg.query("INSERT INTO slips(id,order_id,storage_key,mime,created,status,note) VALUES($1,$2,'private-slip','image/png','2026-09-01T12:00:00Z','รอตรวจสอบ','')",[crypto.randomUUID(),waiting.id]);
 assert.equal((await api.GET(req({}))).status,401);assert.equal((await api.GET(req({id:mine.id}))).status,401);assert.equal((await api.POST(post(guest.token))).status,401);assert.equal(calls,0,'anonymous requests must not read order data');
 user={id:'alice',email:'alice@example.test'};
 let response=await api.GET(req({})),d=await response.json();assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal(Number(d.total),3);assert.equal(d.orders.length,3);assert.ok(d.orders.every(o=>![other.id,guest.id].includes(o.id)));assert.equal(d.orders[0].customer,undefined,'summary excludes recipient data');
 response=await api.GET(req({id:mine.id}));d=await response.json();assert.equal(d.order.items,mine.snapshot);assert.equal(Number(d.order.total),64400);assert.equal(Number(d.order.subtotal),54400);assert.equal(Number(d.order.coupon_discount),1000);assert.equal(Number(d.order.vat),3559);assert.equal(d.order.customer,'ชื่อที่บันทึกตอนสั่ง');assert.match(d.order.address,/ที่อยู่ตอนสั่ง/);assert.equal(d.order.member_id,undefined);
 assert.equal((await api.GET(req({id:other.id}))).status,404);assert.equal((await api.GET(req({id:guest.id}))).status,404);assert.equal((await api.GET(req({id:crypto.randomUUID()}))).status,404);
 d=await(await api.GET(req({query:'0000'}))).json();assert.equal(d.orders.length,1);assert.equal(d.orders[0].id,mine.id);
 for(const query of ['FB-'+mine.id.slice(0,8).toUpperCase(),'TH-'+mine.id]){d=await(await api.GET(req({query}))).json();assert.equal(d.orders.length,1);assert.equal(d.orders[0].id,mine.id)}
 d=await(await api.GET(req({query:'FB-'+other.id.slice(0,8)}))).json();assert.equal(d.orders.length,0);d=await(await api.GET(req({query:"' OR 1=1 --"}))).json();assert.equal(d.orders.length,0);
 d=await(await api.GET(req({query:'%'}))).json();assert.equal(Number(d.total),3,'LIKE wildcard treated as literal');
 d=await(await api.GET(req({filter:'waiting'}))).json();assert.equal(d.orders.length,1);assert.equal(d.orders[0].id,waiting.id);assert.equal(Number(d.orders[0].pending_slips),1);
 d=await(await api.GET(req({filter:'cancelled'}))).json();assert.equal(d.orders[0].id,cancelled.id,'cancelled history remains visible');
 for(const q of [{page:'0'},{limit:'51'},{filter:'invalid'},{query:'a'.repeat(101)},{id:'x'.repeat(101)}])assert.equal((await api.GET(req(q))).status,400);
 for(let i=0;i<310;i++)await add('alice');d=await(await api.GET(req({page:'31',limit:'10'}))).json();assert.equal(Number(d.total),313);assert.equal(d.orders.length,10,'orders beyond 300 can be opened');
 assert.equal((await api.POST(post(guest.token,'https://attacker.test'))).status,403);assert.equal((await api.POST(post(other.token))).status,404);assert.equal((await api.POST(post(guest.token))).status,200);assert.equal((await api.POST(post(guest.token))).status,200,'claim is idempotent');assert.equal((await api.GET(req({id:guest.id}))).status,200);
 user={id:'bob',email:'bob@example.test'};assert.equal((await api.GET(req({id:mine.id}))).status,404);assert.equal((await api.POST(post(guest.token))).status,404);d=await(await api.GET(req({}))).json();assert.equal(d.orders.length,1);assert.equal(d.orders[0].id,other.id);
 const items=view.purchasedItems(mine.snapshot);assert.equal(items[0].price,82);assert.equal(items[1].qty,200);assert.equal(items.reduce((s,i)=>s+i.qty*i.price,0),55400);assert.equal(view.purchasedItems('{invalid'),null);assert.equal(view.purchasedItems('[{"name":"bad","qty":-2,"price":100}]'),null);assert.equal(view.purchasedItems('null'),null);
 for(const value of [guest.token,'https://shop.test/payment?token='+guest.token,'/track?token='+guest.token])assert.equal(view.savedOrderToken(value),guest.token);assert.throws(()=>view.savedOrderToken('0001'));
 assert.equal(view.memberStatus({status:'ยกเลิก',payment:'ชำระแล้ว',pending_slips:1}).label,'ยกเลิก');assert.equal(view.memberStatus({status:'รอชำระเงิน',payment:'รอชำระ',pending_slips:1}).label,'รอตรวจสลิป');
 await pg.close();console.log('PASS member history: account isolation, saved items/prices/address/totals, order 0000, legacy and tracking search, literal wildcards, filters, pagination beyond 300, private caching and safe guest-order linking.');
})().catch(e=>{console.error(e);process.exit(1)});
