const {PGlite}=require('@electric-sql/pglite');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{const db=new PGlite();await db.exec('CREATE ROLE anon; CREATE ROLE authenticated;');await db.exec(fs.readFileSync('supabase/01-schema.sql','utf8'));await db.exec(fs.readFileSync('supabase/02-products.sql','utf8'));assert.equal((await db.query('SELECT count(*)::int AS n FROM products')).rows[0].n,40);
await db.query("INSERT INTO members(id,email,name,phone,address,postcode,updated) VALUES ('m','test@example.test','Test','0','address','10000','2026-09-06')");await db.query("INSERT INTO admin_users(member_id,permissions,active,updated) VALUES ('m','[\"sales\"]',1,'2026-09-06')");
await db.query("INSERT INTO orders(id,token,created,customer,phone,address,tax,items,subtotal,shipping,vat,total,status,carrier,tracking,payment,member_id) VALUES ('o','token','2026-09-05T17:00:00.000Z','Test','0','address','','[]',107000,5000,7000,112000,'ส่งสำเร็จ','','','ชำระแล้ว','m')");
function sql(file,prefix){const source=fs.readFileSync(file,'utf8');const matches=[...source.matchAll(/prepare\((['"])(.*?)\1\)/g)];const s=matches.find(m=>m[2].startsWith(prefix))?.[2];if(!s)throw Error('Missing SQL '+prefix);let n=0;return s.replaceAll('?',()=>'$'+(++n))}
const r=await db.query(sql('app/api/sales/route.ts','SELECT to_char'),['YYYY-MM-DD HH24:00','2026-09-05T17:00:00.000Z','2026-09-06T17:00:00.000Z']);assert.equal(r.rows[0].bucket,'2026-09-06 00:00');assert.equal(Number(r.rows[0].goods)-Number(r.rows[0].vat),100000);
await db.query(sql('app/api/admin-users/route.ts','SELECT id,name,email'),['owner','test','test']);
const imageSql=sql('app/api/product-images/route.ts','INSERT INTO product_images');for(let i=0;i<5;i++){assert.equal((await db.query(imageSql,['i'+i,'SX','key'+i,'image/png','SX'])).rows.length,1)}assert.equal((await db.query(imageSql,['i5','SX','key5','image/png','SX'])).rows.length,0);
await db.query("INSERT INTO documents(order_id,type,created,payload) VALUES ('o','receipt','2026-09-06','{}') ON CONFLICT(order_id,type) DO NOTHING");await db.query("INSERT INTO documents(order_id,type,created,payload) VALUES ('o','receipt','2026-09-06','{}') ON CONFLICT(order_id,type) DO NOTHING");assert.equal((await db.query('SELECT count(*)::int AS n FROM documents')).rows[0].n,1);
await db.exec('SET ROLE anon;');await assert.rejects(()=>db.query('SELECT * FROM orders'));await db.exec('RESET ROLE;');await db.close();console.log('PASS PostgreSQL schema, 40 products, VAT reports, member search, image cap, document uniqueness, direct client access denied.');})().catch(e=>{console.error(e);process.exit(1)});
