'use client';
import {useEffect,useState} from 'react';
import {Bell,Send,Settings,RefreshCw} from 'lucide-react';
import './style.css';
type SettingsType={cart_enabled:boolean;reorder_enabled:boolean;cart_hours:number;reorder_days:number;last_job_at?:string};
export default function NotificationsAdmin(){
 const [data,setData]=useState<any>(null),[settings,setSettings]=useState<SettingsType>({cart_enabled:false,reorder_enabled:false,cart_hours:3,reorder_days:30}),[form,setForm]=useState({kind:'promotion',title:'🔥 โปรโมชั่นจาก FACTORBOXES',body:'เลือกกล่องที่ใช่ พร้อมข้อเสนอสำหรับคุณ ดูรายละเอียดในหน้าร้าน',url:'/store',coupon:''}),[id,setId]=useState(''),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function load(){try{const r=await fetch('/api/admin-notifications',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setSettings(d.settings)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{setId(crypto.randomUUID());void load()},[]);
 async function post(body:unknown){const r=await fetch('/api/admin-notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);return d}
 function edit(p:Partial<typeof form>){setForm(s=>({...s,...p}));setPreview(null);setMessage('');setId(crypto.randomUUID())}
 async function action(kind:string){if(busy)return;setBusy(true);setError('');setMessage('');try{
 if(kind==='preview'){const d=await post({...form,id,action:kind});setPreview(d)}
 if(kind==='send'){const d=await post({...form,id,action:kind});setMessage('บันทึกข้อความถึง '+d.recipients+' บัญชี และเพิ่มเข้าคิวส่งแล้ว');setPreview(null);setId(crypto.randomUUID());await load()}
 if(kind==='settings'){await post({action:kind,settings});setMessage('บันทึกการเตือนอัตโนมัติแล้ว');await load()}
 if(kind==='process'){await post({action:kind});setMessage('ตรวจเงื่อนไขและเริ่มประมวลผลคิวแล้ว กดรีเฟรชเพื่อดูผล');await load()}
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="push-admin"><div className="push-admin-intro"><div><h2><Bell/>ภาพรวมการแจ้งเตือน</h2><p>อัปเดตออเดอร์อัตโนมัติ พร้อมข่าวสารที่ลูกค้าเลือกรับ</p></div><button className="admin-outline" onClick={load}><RefreshCw size={17}/>รีเฟรช</button></div>{error&&<p className="admin-feedback" role="alert">{error}</p>}{message&&<p className="admin-feedback" role="status">{message}</p>}
 <div className="push-admin-stats">{[['เปิดรับข่าวสาร',data?.stats?.opted_in],['อุปกรณ์รับ Push',data?.stats?.devices],['คิวรอส่ง',data?.stats?.queued],['Push service รับแล้ว',data?.stats?.accepted]].map(([label,n])=><article key={label}><small>{label}</small><strong>{n??'—'}</strong></article>)}</div>
 <div className="push-admin-ready"><span className={data?.configured?'ready':'waiting'}>● {data?.configured?'ตั้งค่ากุญแจ Push แล้ว':'รอตั้งค่า WEB_PUSH ใน Vercel'}</span><small>รับแล้ว = บริการ Push รับข้อความ ไม่ยืนยันว่าลูกค้าเห็นหรืออ่านแล้ว · ส่งไม่สำเร็จ {data?.stats?.failed||0} · ข้าม {data?.stats?.skipped||0}</small></div>
 <section className="push-admin-card"><h3>แจ้งสถานะออเดอร์ 4 ขั้นตอน</h3><div className="push-order-flow"><span>✅ รับคำสั่งซื้อ</span><span>💰 ยืนยันชำระเงิน</span><span>📦 กำลังแพ็ค</span><span>🚚 จัดส่ง + Tracking</span></div><p>สร้างข้อความจากสถานะที่บันทึกจริง · เฉพาะออเดอร์ที่ผูกสมาชิก · ไม่ส่งสถานะเก่าย้อนหลังเมื่อเริ่มใช้ระบบ</p></section>
 <div className="push-admin-columns"><section className="push-admin-card"><h3><Send size={20}/>ส่งโค้ด / โปรโมชั่น</h3><p>ส่งให้สมาชิกที่เปิดรับข่าวสารเท่านั้น</p><label>ประเภท<select value={form.kind} onChange={e=>edit({kind:e.target.value,title:e.target.value==='coupon'?'🎁 มีโค้ดส่วนลดใหม่':'🔥 โปรโมชั่นจาก FACTORBOXES'})}><option value="promotion">🔥 โปรโมชั่นลดราคา</option><option value="coupon">🎁 โค้ดส่วนลดใหม่</option></select></label>{form.kind==='coupon'&&<label>เลือก CODE ที่เปิดใช้<select value={form.coupon} onChange={e=>edit({coupon:e.target.value})}><option value="">เลือกโค้ด</option>{data?.coupons.map((c:any)=><option key={c.code} value={c.code}>{c.code}{c.scope==='special'?' (โค้ดพิเศษ)':''}</option>)}</select></label>}<label>หัวข้อ<input value={form.title} maxLength={80} onChange={e=>edit({title:e.target.value})}/></label><label>ข้อความ<textarea value={form.body} maxLength={220} rows={3} onChange={e=>edit({body:e.target.value})}/></label><label>เมื่อแตะข้อความ<select value={form.url} onChange={e=>edit({url:e.target.value})}><option value="/store">เปิดหน้าสินค้า</option><option value="/">เปิดหน้าแรก / ใบราคา</option><option value="/account/orders">เปิดประวัติออเดอร์</option></select></label><button className="admin-primary" disabled={busy||!data||!id} onClick={()=>action('preview')}>ตรวจข้อความและจำนวนผู้รับ</button>
 {preview&&<div className="push-campaign-preview"><small>ตัวอย่างแจ้งเตือน · {preview.recipients} บัญชี</small><b>{preview.title}</b><p>{preview.body}</p><button className="admin-primary" disabled={busy||!preview.recipients} onClick={()=>action('send')}><Send size={16}/>ยืนยันส่งข้อความนี้</button></div>}
 </section><section className="push-admin-card"><h3><Settings size={20}/>เตือนกลับมาซื้ออัตโนมัติ</h3><label className="push-switch"><input type="checkbox" checked={settings.cart_enabled} onChange={e=>setSettings(s=>({...s,cart_enabled:e.target.checked}))}/>🛒 สินค้าค้างในตะกร้า</label><label>หลังไม่มีการใช้งาน (ชั่วโมง)<input type="number" min={1} max={168} value={settings.cart_hours} onChange={e=>setSettings(s=>({...s,cart_hours:Number(e.target.value)}))}/></label><p>หยุดเตือนเมื่อสั่งซื้อหรือล้างตะกร้า ใช้กับสมาชิกที่เปิดรับการเตือนตะกร้า</p><label className="push-switch"><input type="checkbox" checked={settings.reorder_enabled} onChange={e=>setSettings(s=>({...s,reorder_enabled:e.target.checked}))}/>⭐ ชวนลูกค้าเก่ากลับมาสั่ง</label><label>หลังออเดอร์ล่าสุดที่ชำระแล้ว (วัน)<input type="number" min={7} max={365} value={settings.reorder_days} onChange={e=>setSettings(s=>({...s,reorder_days:Number(e.target.value)}))}/></label><p>เว้นอย่างน้อย 30 วันต่อข้อความชวนกลับมาซื้อ ไม่เตือนหากมีออเดอร์ใหม่</p><button className="admin-primary" disabled={busy||!data} onClick={()=>action('settings')}>บันทึกการเตือนอัตโนมัติ</button><div className="push-job-status"><b>การประมวลผลตามเวลา</b><p>ล่าสุด: {settings.last_job_at?new Date(settings.last_job_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}):'ยังไม่ทำงาน'}</p><small>ชุดเริ่มต้นตรวจวันละครั้ง หากต้องการเตือนตามเวลาระดับนาที ให้ตั้ง Cron เพิ่มตามคู่มือ</small><button className="admin-outline" disabled={busy||!data} onClick={()=>action('process')}>ประมวลผลคิวตอนนี้</button></div></section></div>
 <section className="push-admin-card"><h3>ประวัติแคมเปญล่าสุด</h3>{data?.campaigns.length?data.campaigns.map((c:any)=><div className="push-campaign-row" key={c.id}><span><b>{c.title}</b><small>{new Date(c.created_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</small></span><strong>{c.recipients} บัญชี</strong></div>):<p>ยังไม่มีแคมเปญที่ส่ง</p>}<small>โปรโมชั่นบนหน้าจอส่งช่วง 09:00–20:00 น. สูงสุด 1 แคมเปญต่อบัญชีต่อวัน ข้อความอื่นยังอ่านได้ในประวัติแจ้งเตือน</small></section></div>
}
