import {storageBucket} from '@/lib/storage';
import {z} from 'zod';
import {db,isAdmin} from '@/lib/server';
import {getBranding} from '@/lib/branding-server';
import {imageMime,MAX_SLIP_BYTES} from '@/lib/slip-validation';
export const dynamic='force-dynamic';
const bucket=()=>storageBucket;
const safeLink=(s:string)=>{if(s.startsWith('/')&&!s.startsWith('//')&&!s.includes('\\'))return true;try{return new URL(s).protocol==='https:'}catch{return false}};
export async function GET(request:Request){try{const id=new URL(request.url).searchParams.get('image');if(id){z.string().uuid().parse(id);const row=await db().prepare('SELECT value FROM settings WHERE id=?').bind('banner-image-'+id).first<{value:string}>();if(!row)return new Response('Not found',{status:404});const asset=JSON.parse(row.value);const object=await bucket().get(asset.key);if(!object)return new Response('Not found',{status:404});return new Response(object.body,{headers:{'Content-Type':asset.mime,'Cache-Control':'public,max-age=86400','X-Content-Type-Options':'nosniff'}});}return Response.json({branding:await getBranding()},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'โหลดข้อมูลไม่สำเร็จ'},{status:503});}}
export async function POST(request:Request){let pending:string|null=null;try{if(request.headers.get('origin')!==new URL(request.url).origin||!await isAdmin('branding'))return Response.json({error:'ไม่มีสิทธิ์แก้ไขหน้าร้าน'},{status:403});if(request.headers.get('content-type')?.includes('application/json')){const b=z.object({announcement:z.string().max(200),phone:z.string().regex(/^[+0-9 ()-]{7,30}$/),lineId:z.string().trim().min(1).max(100),lineUrl:z.string().max(500).refine(s=>{if(!s)return true;try{const u=new URL(s);return u.protocol==='https:'&&['line.me','lin.ee'].includes(u.hostname)}catch{return false}}),headline:z.string().trim().min(1).max(150),description:z.string().max(500),eyebrow:z.string().max(150),promoTitle:z.string().max(100),promoNote:z.string().max(200),buttonText:z.string().min(1).max(60),buttonUrl:z.string().max(500).refine(safeLink),bannerMode:z.enum(['designed','image']),bannerImage:z.string(),bannerAlt:z.string().min(1).max(200)}).parse(await request.json());if(b.bannerImage){const id=z.string().uuid().parse(b.bannerImage);if(!await db().prepare('SELECT id FROM settings WHERE id=?').bind('banner-image-'+id).first())throw Error('ไม่พบรูปแบนเนอร์ กรุณาอัปโหลดใหม่');}if(b.bannerMode==='image'&&!b.bannerImage)throw Error('เลือกรูปแบนเนอร์ก่อนบันทึก');await db().prepare('INSERT INTO settings (id,value) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind('branding',JSON.stringify(b)).run();return Response.json({ok:true});}
const max=MAX_SLIP_BYTES+65536;if(Number(request.headers.get('content-length')||0)>max)throw Error('รูปต้องไม่เกิน 4 MB');const reader=request.body?.getReader();if(!reader)throw Error('ไม่มีไฟล์');let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw Error('รูปต้องไม่เกิน 4 MB')}chunks.push(value)}const data=new Uint8Array(size);let offset=0;for(const c of chunks){data.set(c,offset);offset+=c.length}const f=await new Response(data,{headers:{'Content-Type':request.headers.get('content-type')||''}}).formData();const file=f.get('file');if(!file||typeof file==='string'||!file.size||file.size>MAX_SLIP_BYTES)throw Error('เลือกรูปไม่เกิน 4 MB');const bytes=new Uint8Array(await file.arrayBuffer()),mime=imageMime(bytes);if(!mime)throw Error('รองรับ JPG, PNG และ WEBP');const id=crypto.randomUUID();pending='banners/'+id;await bucket().put(pending,bytes,{httpMetadata:{contentType:mime}});await db().prepare('INSERT INTO settings (id,value) VALUES (?,?)').bind('banner-image-'+id,JSON.stringify({key:pending,mime})).run();pending=null;return Response.json({id});}catch(e){if(pending)try{await bucket().delete(pending)}catch{}console.error(e);return Response.json({error:e instanceof z.ZodError?'ตรวจสอบข้อความ เบอร์โทร และลิงก์ให้ถูกต้อง':e instanceof Error?e.message:'บันทึกไม่สำเร็จ'},{status:400});}}
