import {storageBucket} from '@/lib/storage';
import {z} from 'zod';
import {db,isAdmin,catalog} from '@/lib/server';
import {imageMime,MAX_SLIP_BYTES} from '@/lib/slip-validation';
export const dynamic='force-dynamic';
const bucket=()=>storageBucket;
export async function GET(request:Request){try{const id=z.string().uuid().parse(new URL(request.url).searchParams.get('id'));const row=await db().prepare('SELECT storage_key,mime FROM product_images WHERE id=?').bind(id).first<{storage_key:string,mime:string}>();if(!row)return new Response('Not found',{status:404});const object=await bucket().get(row.storage_key);if(!object)return new Response('Not found',{status:404});return new Response(object.body,{headers:{'Content-Type':row.mime,'Cache-Control':'public, max-age=86400','X-Content-Type-Options':'nosniff'}});}catch(e){console.error(e);return new Response('Image unavailable',{status:404});}}
export async function POST(request:Request){let pending:string|null=null;try{if(request.headers.get('origin')!==new URL(request.url).origin||!await isAdmin('products'))return Response.json({error:'ไม่มีสิทธิ์จัดการรูปสินค้า'},{status:403});
if(request.headers.get('content-type')?.includes('application/json')){const b=z.object({action:z.enum(['delete','main']),id:z.string().uuid()}).parse(await request.json());const row=await db().prepare('SELECT * FROM product_images WHERE id=?').bind(b.id).first<any>();if(!row)return Response.json({error:'ไม่พบรูป กรุณาโหลดใหม่'},{status:404});if(b.action==='delete'){await db().prepare('DELETE FROM product_images WHERE id=?').bind(b.id).run();try{await bucket().delete(row.storage_key)}catch(e){console.error(e)}}else if(row.slot!==0){const main=await db().prepare('SELECT id FROM product_images WHERE product_id=? AND slot=0').bind(row.product_id).first<{id:string}>();const queries=[];if(main)queries.push(db().prepare('UPDATE product_images SET slot=9 WHERE id=?').bind(main.id));queries.push(db().prepare('UPDATE product_images SET slot=0 WHERE id=?').bind(row.id));if(main)queries.push(db().prepare('UPDATE product_images SET slot=? WHERE id=?').bind(row.slot,main.id));await db().batch(queries);}return Response.json({ok:true});}
const max=MAX_SLIP_BYTES+65536;if(Number(request.headers.get('content-length')||0)>max)return Response.json({error:'รูปต้องไม่เกิน 4 MB'},{status:413});const reader=request.body?.getReader();if(!reader)throw Error('Missing upload');let size=0;const chunks:Uint8Array[]=[];while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>max){await reader.cancel();return Response.json({error:'รูปต้องไม่เกิน 4 MB'},{status:413});}chunks.push(r.value);}const body=new Uint8Array(size);let offset=0;for(const c of chunks){body.set(c,offset);offset+=c.length;}const form=await new Response(body,{headers:{'Content-Type':request.headers.get('content-type')||''}}).formData();const product=z.string().min(1).max(30).parse(form.get('product'));const replacement=form.get('replace')?z.string().uuid().parse(form.get('replace')):null;const c=await catalog();if(!c.products.some(p=>p.id===product))return Response.json({error:'กรุณาบันทึกสินค้าก่อนเพิ่มรูป'},{status:400});const file=form.get('file');if(!file||typeof file==='string'||!file.size||file.size>MAX_SLIP_BYTES)return Response.json({error:'เลือกรูปไม่เกิน 4 MB'},{status:400});const bytes=new Uint8Array(await file.arrayBuffer()),mime=imageMime(bytes);if(!mime)return Response.json({error:'รองรับ JPG, PNG และ WEBP'},{status:400});const old=replacement?await db().prepare('SELECT storage_key,slot FROM product_images WHERE id=? AND product_id=?').bind(replacement,product).first<{storage_key:string,slot:number}>():null;if(replacement&&!old)return Response.json({error:'ไม่พบรูปเดิม กรุณาโหลดใหม่'},{status:404});const id=crypto.randomUUID();pending='products/'+product+'/'+id;await bucket().put(pending,bytes,{httpMetadata:{contentType:mime}});let saved:any;if(old){saved=await db().prepare('UPDATE product_images SET id=?,storage_key=?,mime=? WHERE id=? AND product_id=? RETURNING id,slot').bind(id,pending,mime,replacement,product).first();}else{saved=await db().prepare('INSERT INTO product_images (id,product_id,storage_key,mime,slot) SELECT ?,?,?,?,s.n FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) s WHERE NOT EXISTS (SELECT 1 FROM product_images p WHERE p.product_id=? AND p.slot=s.n) ORDER BY s.n LIMIT 1 RETURNING id,slot').bind(id,product,pending,mime,product).first();}if(!saved){await bucket().delete(pending);pending=null;return Response.json({error:'สินค้าใส่รูปได้สูงสุด 5 รูป กรุณาลบหรือเปลี่ยนรูปเดิม'},{status:409});}pending=null;if(old)try{await bucket().delete(old.storage_key)}catch(e){console.error(e)}return Response.json({image:{id,slot:saved.slot,url:'/api/product-images?id='+id}});
}catch(e){if(pending)try{await bucket().delete(pending)}catch{}console.error(e);return Response.json({error:'บันทึกรูปไม่สำเร็จ กรุณาลองอีกครั้ง'},{status:400});}}
