'use client';
import {useState,useEffect} from 'react';
export default function Profile({signInPath}:{signInPath:string}){
 const [profile,setProfile]=useState({name:'',email:'',phone:'',address:'',postcode:''}),[registered,setRegistered]=useState(false),[loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[expired,setExpired]=useState(false),[message,setMessage]=useState('');
 async function load(){setLoading(true);setMessage('');try{const r=await fetch('/api/member',{cache:'no-store'});if(r.status===401){setExpired(true);throw Error('เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง')}const d=await r.json() as any;if(!r.ok)throw Error(d.error||'โหลดข้อมูลไม่สำเร็จ');setExpired(false);setRegistered(!!d.member);if(d.member)setProfile({name:d.member.name,email:d.member.email||d.email||'',phone:d.member.phone,address:d.member.address,postcode:d.member.postcode});else setProfile(p=>({...p,email:d.email||''}));setLoaded(true)}catch(e){setMessage((e as Error).message);setLoaded(false)}finally{setLoading(false)}}
 useEffect(()=>{load();const refresh=(e:PageTransitionEvent)=>{if(e.persisted)window.location.reload()};window.addEventListener('pageshow',refresh);return ()=>window.removeEventListener('pageshow',refresh)},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/member',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});if(r.status===401){setExpired(true);throw Error('เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง')}const d=await r.json() as any;if(!r.ok)throw Error(d.error||'บันทึกไม่สำเร็จ');setRegistered(true);setMessage('บันทึกข้อมูลสมาชิกแล้ว ครั้งต่อไปใช้บัญชีเดิม ข้อมูลและที่อยู่จะถูกโหลดให้อัตโนมัติ')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={submit} className="panel form"><h3>{registered?'ข้อมูลสมาชิกของคุณ':'สมัครสมาชิก FACTORBOXES'}</h3><label>อีเมลติดต่อ<input type="email" name="email" required autoComplete="email" inputMode="email" autoCapitalize="none" spellCheck={false} maxLength={254} disabled={loading||!loaded} value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><small>แก้ไขเป็นอีเมลที่คุณใช้งานได้ ช่องนี้ใช้ติดต่อเรื่องคำสั่งซื้อ ไม่เปลี่ยนบัญชีที่ใช้เข้าสู่ระบบ</small><label>ชื่อผู้รับ<input required autoComplete="name" minLength={2} maxLength={100} disabled={loading||!loaded} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>เบอร์โทรศัพท์<input required autoComplete="tel" pattern="0[0-9]{8,9}" inputMode="tel" disabled={loading||!loaded} value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label>ที่อยู่จัดส่ง ตำบล อำเภอ จังหวัด<textarea required autoComplete="street-address" minLength={10} maxLength={1000} disabled={loading||!loaded} value={profile.address} onChange={e=>setProfile({...profile,address:e.target.value})}/></label><label>รหัสไปรษณีย์<input required autoComplete="postal-code" pattern="[0-9]{5}" inputMode="numeric" disabled={loading||!loaded} value={profile.postcode} onChange={e=>setProfile({...profile,postcode:e.target.value})}/></label>{message&&<p role="status" className="notice">{message}</p>}{expired?<a className="primary" href={signInPath} target="_top">เข้าสู่ระบบอีกครั้ง</a>:!loaded&&!loading?<button type="button" className="secondary" onClick={load}>ลองโหลดข้อมูลอีกครั้ง</button>:<button className="primary" disabled={loading||busy||!loaded}>{loading?'กำลังโหลดข้อมูล…':busy?'กำลังบันทึก…':registered?'บันทึกการแก้ไข':'สมัครสมาชิกและบันทึกที่อยู่'}</button>}<a className="secondary" href="/">กลับไปเลือกสินค้า</a><small>ข้อมูลสมาชิกผูกกับบัญชีที่ยืนยันตัวตนแล้ว โปรดใช้บัญชีเดิมเพื่อดูประวัติการสั่งซื้อ</small></form>
}
