'use client';
import {useState,useEffect} from 'react';
import {UserRound,LockKeyhole,Save,CheckCircle2} from 'lucide-react';
export default function Profile({signInPath}:{signInPath:string}){
 const [profile,setProfile]=useState({name:'',email:'',phone:'',address:'',postcode:''}),[registered,setRegistered]=useState(false),[loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[expired,setExpired]=useState(false),[message,setMessage]=useState(''),[saved,setSaved]=useState(false);
 async function load(){setLoading(true);setMessage('');try{const r=await fetch('/api/member',{cache:'no-store'});if(r.status===401){setExpired(true);throw Error('เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง')}const d=await r.json();if(!r.ok)throw Error(d.error||'โหลดข้อมูลไม่สำเร็จ');setExpired(false);setRegistered(!!d.member);if(d.member)setProfile({name:d.member.name,email:d.member.email||d.email||'',phone:d.member.phone,address:d.member.address,postcode:d.member.postcode});else setProfile(p=>({...p,email:d.email||''}));setLoaded(true)}catch(e){setMessage((e as Error).message);setLoaded(false)}finally{setLoading(false)}}
 useEffect(()=>{void load();const refresh=(e:PageTransitionEvent)=>{if(e.persisted)window.location.reload()};window.addEventListener('pageshow',refresh);return ()=>window.removeEventListener('pageshow',refresh)},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||!loaded)return;setBusy(true);setMessage('');setSaved(false);try{const r=await fetch('/api/member',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});if(r.status===401){setExpired(true);throw Error('เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง')}const d=await r.json();if(!r.ok)throw Error(d.error||'บันทึกไม่สำเร็จ');setRegistered(true);setSaved(true);setMessage('บันทึกข้อมูลแล้ว ใช้ที่อยู่นี้สำหรับคำสั่งซื้อครั้งต่อไป') }catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const disabled=loading||!loaded||busy;
 return <form onSubmit={submit} className="member-card member-profile" id="member-profile"><div className="member-section-heading"><span className="member-icon"><UserRound size={26}/></span><div><h2>{registered?'ข้อมูลสมาชิกของคุณ':'ข้อมูลสมาชิกและที่อยู่จัดส่ง'}</h2><p>แก้ไขข้อมูลได้ตลอดเวลา ข้อมูลนี้จะใช้สำหรับคำสั่งซื้อครั้งต่อไป</p></div></div>
 <div className="member-profile-fields"><label className="profile-email">อีเมลติดต่อ<div><input type="email" name="email" required autoComplete="email" inputMode="email" autoCapitalize="none" spellCheck={false} maxLength={254} disabled={disabled} value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/><small>ใช้ติดต่อเรื่องคำสั่งซื้อ การแก้ช่องนี้ไม่เปลี่ยนอีเมลที่ใช้เข้าสู่ระบบ</small></div></label><label className="profile-name">ชื่อผู้รับ<input required autoComplete="name" minLength={2} maxLength={100} disabled={disabled} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label className="profile-phone">เบอร์โทรศัพท์<input type="tel" required autoComplete="tel" pattern="0[0-9]{8,9}" maxLength={10} inputMode="tel" disabled={disabled} value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label className="profile-address">ที่อยู่จัดส่ง ตำบล อำเภอ จังหวัด<textarea required autoComplete="street-address" minLength={10} maxLength={1000} rows={3} disabled={disabled} value={profile.address} onChange={e=>setProfile({...profile,address:e.target.value})}/></label><label className="profile-postcode">รหัสไปรษณีย์<input required autoComplete="postal-code" pattern="[0-9]{5}" maxLength={5} inputMode="numeric" disabled={disabled} value={profile.postcode} onChange={e=>setProfile({...profile,postcode:e.target.value})}/></label></div>
 {message&&<p role="status" className={'member-feedback '+(saved?'success':'')}>{saved&&<CheckCircle2 size={18}/>} {message}</p>}
 {expired?<a className="member-primary" href={signInPath} target="_top">เข้าสู่ระบบอีกครั้ง</a>:!loaded&&!loading?<button type="button" className="member-outline" onClick={load}>ลองโหลดข้อมูลอีกครั้ง</button>:<button className="member-primary member-save" disabled={disabled}><LockKeyhole size={18}/>{loading?'กำลังโหลดข้อมูล…':busy?'กำลังบันทึก…':registered?'บันทึกการแก้ไข':'บันทึกสมาชิกและที่อยู่'}<Save size={17}/></button>}
 </form>;
}
