'use client';
import {useBranding} from './branding-context';
import {telephone} from '@/lib/branding';
import {Package,ShoppingBag,Truck,ArrowUpRight,UserRound} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export function Header({count=0,onCart}:{count?:number,onCart?:()=>void}){const brand=useBranding();return <><div className="announcement">{brand.announcement} <span>โทร. {brand.phone}</span></div><header><a className="brand" href="/"><img className="brandlogo" src="/factorboxes-logo.jpeg" alt="โลโก้ FACTORBOXES"/><span>FACTOR<span className="brandlight">BOXES</span><small>PACK YOUR NEXT POSSIBILITY</small></span></a><nav><a href="/" className="navshop">เลือกซื้อสินค้า</a><a href="/track"><Truck size={18}/>ติดตามพัสดุ</a><a href="/account" aria-label="สมาชิกและที่อยู่"><UserRound size={18}/>สมาชิก</a>{onCart&&<button className="cartbtn" onClick={onCart}><ShoppingBag size={19}/><span>ตะกร้า</span><b>{count}</b></button>}</nav></header></>}
export function Footer(){const brand=useBranding();return <footer><a className="brand" href="/"><img className="brandlogo" src="/factorboxes-logo.jpeg" alt="โลโก้ FACTORBOXES"/>FACTORBOXES</a><p>กล่องที่ใช่ สำหรับทุกการจัดส่ง</p><div><a href={telephone(brand.phone)}>{brand.phone}</a>{brand.lineUrl?<a href={brand.lineUrl} target="_blank" rel="noreferrer">LINE: {brand.lineId}</a>:<span>LINE: {brand.lineId}</span>}<a href="/account/orders">ประวัติคำสั่งซื้อ / ติดตาม</a></div><small>© 2026 FACTORBOXES</small></footer>}
export function Choice({value,onChange,items,label}:{value:string,onChange:(v:string)=>void,items:string[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select>}
export async function api(body:unknown){const r=await fetch('/api/shop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as Record<string,any>;if(!r.ok)throw new Error(d.error||'เกิดข้อผิดพลาด');return d;}
