import {getCarriers} from '@/lib/carriers-server';
import {carrierListSchema} from '@/lib/carriers';
import {validCoupon} from '@/lib/coupons';
import {identity} from '@/lib/member';
import {z} from 'zod';
import {db,isAdmin,catalog} from '@/lib/server';
import {statuses,totals,categories} from '@/lib/catalog';
export const dynamic='force-dynamic';
const product=z.object({id:z.string().min(1).max(30),category:z.enum(categories).default('กล่อง'),sku:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{1,30}$/),name:z.string().min(1).max(100),size:z.string().max(100),price:z.number().int().min(1).max(10000000),active:z.number().int().min(0).max(1),tiers:z.array(z.number().int().min(1).max(10000000)).length(5)});
export async function GET(request:Request){try{const u=new URL(request.url);if(u.searchParams.get('admin')){if(!await isAdmin())return Response.json({error:'ไม่มีสิทธิ์เข้าถึง'},{status:403});return Response.json({...await catalog(),carriers:await getCarriers(),orders:await isAdmin('orders')?(await db().prepare("SELECT orders.*, (SELECT COUNT(*) FROM slips WHERE slips.order_id=orders.id AND slips.status='รอตรวจสอบ') AS pending_slips FROM orders ORDER BY created DESC LIMIT 300").all()).results:[]},{headers:{'Cache-Control':'no-store'}});}return Response.json(await catalog(),{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'โหลดข้อมูลไม่สำเร็จ กรุณาลองอีกครั้ง'},{status:503});}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'คำขอไม่ถูกต้อง'},{status:403});const body=z.record(z.unknown()).parse(await request.json());
if(body.action==='track'){const token=z.string().min(20).max(100).parse(body.token);const o=await db().prepare('SELECT id,order_no,created,status,carrier,tracking,total,payment FROM orders WHERE token=?').bind(token).first();return o?Response.json({order:o,slips:(await db().prepare('SELECT created,status,note FROM slips WHERE order_id=? ORDER BY created DESC').bind(o.id).all()).results},{headers:{'Cache-Control':'no-store'}}):Response.json({error:'ไม่พบคำสั่งซื้อ กรุณาตรวจสอบรหัสติดตาม'},{status:404});}
if(body.action==='order'){const b=z.object({customer:z.string().trim().min(2).max(100),phone:z.string().regex(/^0[0-9]{8,9}$/),address:z.string().trim().min(10).max(1000),postcode:z.string().regex(/^[0-9]{5}$/),tax:z.string().max(1000),items:z.array(z.object({id:z.string(),qty:z.number().int().min(1).max(100000)})).min(1).max(100),key:z.string().uuid(),coupon:z.string().trim().max(30).optional()}).parse(body);const existing=await db().prepare('SELECT id,order_no,token,total FROM orders WHERE id=?').bind(b.key).first();if(existing)return Response.json({order:existing});const c=await catalog();const items=b.items.map(i=>{const p=c.products.find((p:any)=>p.id===i.id&&p.active);if(!p)throw new Error('Invalid product');return {...p,qty:i.qty} as {price:number,qty:number};});const before=totals(items,c.settings);let coupon=null;try{if(b.coupon)coupon=await validCoupon(b.coupon,before.tierSubtotal)}catch(e){return Response.json({error:(e as Error).message},{status:400})}const t=totals(items,c.settings,coupon);const token=crypto.randomUUID();const user=await identity();await db().prepare('INSERT INTO orders (id,token,created,customer,phone,address,tax,items,subtotal,shipping,vat,total,status,carrier,tracking,payment,member_id,coupon_code,coupon_discount) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(b.key,token,new Date().toISOString(),b.customer,b.phone,b.address+' '+b.postcode,b.tax,JSON.stringify(t.pricedItems),t.subtotal,t.shipping,t.vat,t.total,'รอชำระเงิน','','','รอชำระ',user?.id||null,coupon?.code||'',t.couponDiscount).run();const numbered=await db().prepare('SELECT id,order_no,token,total FROM orders WHERE id=?').bind(b.key).first<{id:string,order_no:number,token:string,total:number}>();return Response.json({order:numbered,demo:!c.settings.priceConfirmed});}
if(!await isAdmin())return Response.json({error:'ไม่มีสิทธิ์เข้าถึง'},{status:403});
if(body.action==='products'){if(!await isAdmin('products'))return Response.json({error:'ไม่มีสิทธิ์แก้ไขสินค้า'},{status:403});const ps=z.array(product).min(1).max(100).parse(body.products);if(ps.some(p=>p.price!==p.tiers[0]||p.tiers.some((v,i)=>i>0&&v>p.tiers[i-1])))return Response.json({error:'ราคาต้องลดหลั่นตามเรท และราคาแรกต้องตรงกับเรท 750 บาท'},{status:400});if(new Set(ps.map(p=>p.sku)).size!==ps.length)return Response.json({error:'รหัสสินค้าต้องไม่ซ้ำกัน'},{status:400});if(new Set(ps.map(p=>p.id)).size!==ps.length)throw new Error('Duplicate products');await db().batch([...ps.map(p=>db().prepare('UPDATE products SET sku=NULL WHERE id=?').bind(p.id)),...ps.map(p=>db().prepare('INSERT INTO products (id,name,size,price,active,sku,category) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,size=excluded.size,price=excluded.price,active=excluded.active,sku=excluded.sku,category=excluded.category').bind(p.id,p.name,p.size,p.price,p.active,p.sku,p.category)),db().prepare('INSERT INTO settings (id,value) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind('price-tiers-20260906',JSON.stringify(Object.fromEntries(ps.map(p=>[p.id,p.tiers]))))]);}
else if(body.action==='carriers'){if(!await isAdmin('settings'))return Response.json({error:'ไม่มีสิทธิ์แก้ไขรายชื่อขนส่ง'},{status:403});const names=carrierListSchema.parse(body.carriers);await db().prepare('INSERT INTO settings (id,value) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind('shipping-carriers',JSON.stringify(names)).run();}
else if(body.action==='settings'){if(!await isAdmin('settings'))return Response.json({error:'ไม่มีสิทธิ์แก้ไขการตั้งค่า'},{status:403});const s=z.object({vatRate:z.number().min(0).max(25),freeShipping:z.number().min(0).max(1000000),shippingFee:z.number().min(0).max(100000),priceConfirmed:z.boolean(),bank:z.string().max(1000),bankName:z.string().trim().max(100).default(''),accountName:z.string().trim().max(200).default(''),accountNumber:z.string().trim().max(50).default(''),seller:z.string().min(1).max(200),sellerTax:z.string().max(13),sellerAddress:z.string().max(1000)}).parse(body.settings);await db().prepare('INSERT INTO settings (id,value) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind('shop',JSON.stringify(s)).run();}
else if(body.action==='update'){if(!await isAdmin('orders'))return Response.json({error:'ไม่มีสิทธิ์แก้ไขคำสั่งซื้อ'},{status:403});const b=z.object({id:z.string().uuid(),status:z.enum(statuses as [string,...string[]]),carrier:z.string().max(80),tracking:z.string().max(100),payment:z.enum(['รอชำระ','ชำระแล้ว']),transferred_at:z.string().datetime({offset:true}).nullable().optional(),tax:z.string().max(1000).optional()}).parse(body);const previous=await db().prepare('SELECT carrier FROM orders WHERE id=?').bind(b.id).first<{carrier:string}>();if(!previous)return Response.json({error:'ไม่พบคำสั่งซื้อ'},{status:404});if(b.carrier&&b.carrier!==previous.carrier&&!(await getCarriers()).includes(b.carrier))return Response.json({error:'บริษัทขนส่งนี้ไม่อยู่ในรายการ กรุณารีเฟรชแล้วเลือกใหม่'},{status:400});if(['จัดส่งแล้ว','ส่งสำเร็จ'].includes(b.status)&&(!b.carrier.trim()||!b.tracking.trim()))return Response.json({error:'กรุณาระบุขนส่งและเลขพัสดุ'},{status:400});await db().prepare('UPDATE orders SET status=?,carrier=?,tracking=?,payment=?,transferred_at=?,tax=COALESCE(?,tax) WHERE id=?').bind(b.payment==='ชำระแล้ว'&&['รอยืนยัน','รอชำระเงิน'].includes(b.status)?'ชำระแล้ว':b.payment==='รอชำระ'&&b.status==='ชำระแล้ว'?'รอชำระเงิน':b.status,b.carrier,b.tracking,b.payment,b.transferred_at||null,b.tax??null,b.id).run();}else return Response.json({error:'คำขอไม่ถูกต้อง'},{status:400});return Response.json({ok:true});
}catch(e){console.error(e);return Response.json({error:e instanceof z.ZodError?'กรุณาตรวจสอบข้อมูลให้ครบถ้วน':'บันทึกไม่สำเร็จ กรุณาลองอีกครั้ง'},{status:400});}}
