import {orderNumber} from '@/lib/order-number';
import {getBranding} from '@/lib/branding-server';
import {requireChatGPTUser} from '@/app/chatgpt-auth';
import {db,isAdmin,catalog} from '@/lib/server';
import {money} from '@/lib/catalog';
import PrintButton from './print-button';
export const dynamic='force-dynamic';
const date=(s:string)=>new Date(s).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'});
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const q=await searchParams;return <Protected params={q}/>}
async function Protected({params:q}:{params:Record<string,string|undefined>}){await requireChatGPTUser('/print?'+new URLSearchParams(Object.entries(q).filter((v):v is [string,string]=>!!v[1])).toString());if(!await isAdmin('orders'))return <p>ไม่มีสิทธิ์เข้าถึงเอกสาร</p>;try{let o:any,seller:any,title='',num='',issued='';const label=!!q.order;if(label){o=await db().prepare('SELECT * FROM orders WHERE id=?').bind(q.order!).first<any>();if(!o)return <p>ไม่พบคำสั่งซื้อ</p>;o.items=JSON.parse(o.items);const c=await catalog();seller={phone:(await getBranding()).phone,name:c.settings.seller,address:c.settings.sellerAddress,tax:c.settings.sellerTax};title='ใบปะหน้าหีบห่อ';}else{const doc=await db().prepare('SELECT * FROM documents WHERE id=?').bind(q.doc||'').first<any>();if(!doc)return <p>ไม่พบเอกสาร</p>;const p=JSON.parse(doc.payload);o=p.order;seller=p.seller;title=doc.type==='tax'?'ใบเสร็จรับเงิน / ใบกำกับภาษี':'ใบเสร็จรับเงิน';num=(doc.type==='tax'?'TAX':'RC')+'-'+String(doc.id).padStart(7,'0');issued=doc.created;}
return <main className={'printpage '+(label?'packinglabel':'financialdoc')}><PrintButton/><header className="documenthead"><div><h2>{seller.name}</h2><p className="preline">{seller.address||''}</p>{seller.tax&&<p>เลขประจำตัวผู้เสียภาษี {seller.tax}</p>}<p>โทร. {seller.phone||'062-610-6289'}</p></div><div><h1>{title}</h1>{num&&<p>เลขที่ {num}</p>}{issued&&<p>วันที่ออก {date(issued)}</p>}<p>อ้างอิง {orderNumber(o)}</p><p>สั่งซื้อ {date(o.created)}</p></div></header><section className="recipient"><h3>{label?'ผู้รับ / จัดส่งถึง':'ลูกค้า / ผู้ซื้อ'}</h3><b>{o.customer}</b><p className="preline">{o.address}</p><p>โทรศัพท์ {o.phone}</p>{!label&&o.tax&&<p className="preline buyerinfo">ข้อมูลใบกำกับภาษี: {'\n'+o.tax}</p>}</section>{label&&<p className="parcelmeta">ขนส่ง: {o.carrier||'________________'}　เลขพัสดุ: {o.tracking||'________________'}　หีบห่อที่ ____ / ____</p>}<table className="documenttable"><thead><tr><th>ลำดับ</th><th>รายการสินค้า / ขนาด</th><th>จำนวน (ใบ)</th>{!label&&<><th>ราคา/ใบ (รวม VAT)</th><th>จำนวนเงิน</th></>}</tr></thead><tbody>{o.items.map((i:any,n:number)=><tr key={n}><td>{n+1}</td><td>{i.name}<small>รหัส {i.sku||i.id}</small><small>{i.size} ซม.</small></td><td>{i.qty.toLocaleString()}</td>{!label&&<><td>{money(i.price)}</td><td>{money(i.price*i.qty)}</td></>}</tr>)}</tbody><tfoot><tr><td colSpan={2}>รวมจำนวนสินค้า</td><td>{o.items.reduce((n:number,i:any)=>n+i.qty,0).toLocaleString()} ใบ</td>{!label&&<td colSpan={2}/>}</tr></tfoot></table>{!label&&<><section className="documenttotals">{o.couponDiscount>0&&<><p><span>ยอดสินค้าตามเรท</span><b>{money(o.subtotal+o.couponDiscount)} บาท</b></p><p><span>ส่วนลด CODE {o.couponCode}</span><b>−{money(o.couponDiscount)} บาท</b></p></>}<p><span>มูลค่าสินค้าก่อน VAT</span><b>{money(o.subtotal-o.vat)} บาท</b></p><p><span>ภาษีมูลค่าเพิ่มสินค้า</span><b>{money(o.vat)} บาท</b></p><p><span>ค่าจัดส่ง (แยกจากฐาน VAT สินค้า)</span><b>{money(o.shipping)} บาท</b></p><p><span>ยอดรับชำระรวม</span><b>{money(o.total)} บาท</b></p></section><p className="transferline">ชำระโดยโอนเงิน · วันเวลาโอน: {o.transferredAt?date(o.transferredAt):'________________'} (ประเทศไทย)</p><div className="signatures"><div><span>ลงชื่อ ____________________</span><b>ผู้รับเงิน</b><p>วันที่ ____________________</p></div><div className="stamp"><span>ช่องตราประทับบริษัท</span></div><div><span>ลงชื่อ ____________________</span><b>ผู้รับสินค้า</b><p>วันที่ ____________________</p></div></div></>}<small className="docfoot">{label?'ตรวจสอบจำนวนสินค้าก่อนปิดหีบห่อ':'เอกสารจัดพิมพ์จากระบบ FACTORBOXES'}</small></main>}catch(e){console.error(e);return <p>โหลดเอกสารไม่สำเร็จ กรุณากลับไปลองใหม่ในหลังบ้าน</p>}}
