'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowUpRight,Download,Phone,MessageCircle,Globe,Smartphone,FileText,Check,Copy} from 'lucide-react';
import {useBranding} from '../branding-context';
import {telephone} from '@/lib/branding';
const sheet='/price-lists/factorboxes-price-list.jpg';
export default function Guide(){
 const brand=useBranding();const [message,setMessage]=useState('');
 async function copyLine(){try{await navigator.clipboard.writeText(brand.lineId);setMessage('คัดลอก LINE ID แล้ว เปิด LINE เพื่อค้นหาและเพิ่มเพื่อน')}catch{setMessage('LINE ID: '+brand.lineId+' — แตะค้างที่ชื่อ LINE เพื่อคัดลอก')}}
 return <div className="fb-guide"><header><a className="guide-brand" href="/store"><img src="/app-icons/icon-192.png" alt="" width="40" height="40"/><b>FACTOR<span>BOXES</span></b></a><a href="/store"><ArrowLeft size={16}/>หน้าร้าน</a></header><main>
 <section className="guide-hero"><p className="guide-eyebrow">FACTORBOXES · ALWAYS WITH YOU</p><h1>ร้านกล่องของคุณ<br/><em>อยู่ใกล้แค่ปลายนิ้ว</em></h1><p>ติดตั้งทางลัด ดูราคา และติดต่อร้าน<br/>ครบในหน้าเดียว</p><nav><a href="#install"><Smartphone/>ติดตั้งแอป</a><a href="#prices"><FileText/>ใบราคา</a><a href="#contact"><MessageCircle/>ติดต่อเรา</a></nav></section>
 <section className="guide-card guide-install" id="install"><div><span className="guide-kicker">01 / เพิ่มร้านลงมือถือ</span><h2>กดครั้งเดียว ก็เข้าร้านได้</h2><p>เพิ่มไอคอน FACTORBOXES ลงหน้าจอ<br/>ไม่ต้องค้นหาเว็บไซต์ใหม่ทุกครั้ง</p><a className="guide-primary" href="/install"><Smartphone size={20}/>ดูวิธีติดตั้งบนมือถือ<ArrowUpRight size={18}/></a><small>รองรับ iPhone และ Android · ไม่ต้องผ่าน App Store</small></div><div className="guide-app"><img src="/app-icons/icon-192.png" alt="ไอคอนแอป FACTORBOXES" width="96" height="96"/><b>FACTORBOXES</b><span><Check size={16}/>เลือกซื้อ · เช็กออเดอร์ · ติดตามพัสดุ</span></div></section>
 <section className="guide-card" id="prices"><div className="guide-section-title"><div><span className="guide-kicker">02 / เลือกขนาดที่ใช่</span><h2>ใบราคากล่องไปรษณีย์</h2><p>เทียบราคา 5 เรท ตามยอดสั่งซื้อของคุณ</p></div><a className="guide-outline" href={sheet} download="factorboxes-price-list.jpg"><Download size={18}/>ดาวน์โหลด</a></div><div className="guide-tiers">{['750','5,000','15,000','25,000','50,000'].map(x=><span key={x}>ยอดสั่งซื้อ<b>฿{x}</b></span>)}</div><a className="guide-sheet" href={sheet} target="_blank" rel="noreferrer" aria-label="เปิดใบราคาขนาดเต็ม"><img src={sheet} alt="ใบราคากล่อง FACTORBOXES 40 รายการ แบ่งตามยอดสั่งซื้อ 5 เรท" loading="lazy"/></a><div className="guide-price-bottom"><span>แตะภาพเพื่อเปิดขนาดเต็ม แล้วใช้นิ้วขยายดูราคา</span><a href={sheet} target="_blank" rel="noreferrer">ดูภาพใหญ่ ↗</a></div><p className="guide-note">ใบราคาสำหรับประกอบการเลือกซื้อ กรุณาตรวจสอบราคาปัจจุบันและยอดสุทธิในตะกร้าก่อนยืนยันออเดอร์</p><a className="guide-primary" href="/store">เลือกซื้อกล่อง<ArrowUpRight size={19}/></a></section>
 <section id="contact"><span className="guide-kicker">03 / ยินดีช่วยคุณเลือกกล่อง</span><h2>คุยกับเราได้เลย</h2><p>สอบถามขนาด ราคา หรือรายละเอียดการสั่งซื้อ</p><div className="guide-contacts"><a className="guide-contact phone" href={telephone(brand.phone)}><Phone/><span><small>โทรสอบถาม</small><b>{brand.phone}</b></span><ArrowUpRight/></a>{brand.lineUrl?<a className="guide-contact line" href={brand.lineUrl} target="_blank" rel="noreferrer"><MessageCircle/><span><small>เพิ่มเพื่อน LINE</small><b>{brand.lineId}</b></span><ArrowUpRight/></a>:<button className="guide-contact line" onClick={copyLine}><MessageCircle/><span><small>คัดลอก LINE ID</small><b>{brand.lineId}</b></span><Copy/></button>}{brand.facebookUrl?<a className="guide-contact facebook" href={brand.facebookUrl} target="_blank" rel="noreferrer"><Globe/><span><small>ติดตามข่าวสาร</small><b>Facebook ของร้าน</b></span><ArrowUpRight/></a>:<a className="guide-contact facebook" href="https://www.facebook.com/search/top?q=Factorboxes" target="_blank" rel="noreferrer"><Globe/><span><small>ค้นหาชื่อ FACTORBOXES</small><b>ค้นหาบน Facebook</b></span><ArrowUpRight/></a>}</div><p role="status" className="guide-note">{message}</p></section>
 </main><footer>PACK YOUR NEXT POSSIBILITY<br/><small>FACTORBOXES · โรงงานผลิตกล่องพัสดุ</small></footer></div>
}
