import {db,isAdmin} from '@/lib/server';
import {accountingDate,csv,billNumber} from '@/lib/accounting';
import {orderNumber} from '@/lib/order-number';
import {documentHTML} from '@/lib/accounting-documents';
import {zipFiles} from '@/lib/zip';
import {storageBucket} from '@/lib/storage';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{if(!await isAdmin('accounting'))return Response.json({error:'ไม่มีสิทธิ์ส่งออกเอกสาร'},{status:403});const q=new URL(request.url).searchParams,from=accountingDate.parse(q.get('from')),through=accountingDate.parse(q.get('through'));if(through<from||(Date.parse(through)-Date.parse(from))/86400000>366)throw Error('เลือกช่วงวันที่ไม่เกิน 366 วัน');const start=from+'T00:00:00+07:00',end=new Date(Date.parse(through+'T00:00:00+07:00')+86400000).toISOString();const startISO=new Date(start).toISOString();
 const docs=(await db().prepare('SELECT * FROM documents WHERE created>=? AND created<? ORDER BY id LIMIT 501').bind(startISO,end).all()).results;
 const bills=(await db().prepare('SELECT *,due_date::text AS due_date FROM accounting_bills WHERE issued_at>=?::timestamptz AND issued_at<?::timestamptz ORDER BY id LIMIT 501').bind(start,end).all()).results;
 const entries=(await db().prepare('SELECT *,document_date::text AS document_date,due_date::text AS due_date FROM accounting_entries WHERE document_date>=?::date AND document_date<=?::date ORDER BY accounting_entries.document_date,id LIMIT 2001').bind(from,through).all()).results;
 const payments=(await db().prepare('SELECT p.*,e.kind,e.counterparty,e.reference AS document_reference FROM accounting_payments p JOIN accounting_entries e ON e.id=p.entry_id WHERE p.paid_at>=?::timestamptz AND p.paid_at<?::timestamptz ORDER BY p.paid_at LIMIT 2001').bind(start,end).all()).results;
 const orders=(await db().prepare("SELECT id,order_no,customer,total,vat,shipping,transferred_at,created FROM orders WHERE payment='ชำระแล้ว' AND status<>'ยกเลิก' AND COALESCE(transferred_at,created)>=? AND COALESCE(transferred_at,created)<? ORDER BY created LIMIT 2001").bind(startISO,end).all()).results;
 if(docs.length>500||bills.length>500||entries.length>2000||payments.length>2000||orders.length>2000)throw Error('ข้อมูลมากเกินไป กรุณาแบ่งดาวน์โหลดเป็นช่วงวันที่สั้นลง');
 const files:{name:string,data:Buffer}[]=[];let size=0;const add=(name:string,body:string|Buffer)=>{const data=typeof body==='string'?Buffer.from(body):body;size+=data.length+name.length+100;if(size>3500000)throw Error('ไฟล์รวมเกิน 3.5 MB กรุณาลดช่วงวันที่ หรือไม่รวมภาพแนบแล้วดาวน์โหลดภาพแยกในรายการบัญชี');files.push({name,data})};
 const money=(v:unknown)=>(Number(v||0)/100).toFixed(2);
 add('documents.csv',csv([['เลขเอกสาร','ประเภท','วันที่ออก','ออเดอร์','ลูกค้า','สินค้าก่อน VAT','VAT','ขนส่ง','ยอดรวม'],...docs.map(d=>{const o=JSON.parse(d.payload).order;return [(d.type==='tax'?'TAX-':'RC-')+String(d.id).padStart(7,'0'),d.type,d.created,orderNumber(o),o.customer,money(o.subtotal-o.vat),money(o.vat),money(o.shipping),money(o.total)]})]));
 for(const d of docs)add('documents/'+(d.type==='tax'?'TAX-':'RC-')+String(d.id).padStart(7,'0')+'.html',documentHTML(d));
 add('bills.csv',csv([['เลขใบวางบิล','ออเดอร์','วันที่ออก','ครบกำหนด','ยกเลิกเมื่อ','เหตุผล'],...bills.map(b=>[billNumber(b.id),orderNumber((typeof b.payload==='string'?JSON.parse(b.payload):b.payload).order),b.issued_at,b.due_date,b.voided_at,b.void_reason])]));
 for(const b of bills)add('bills/'+billNumber(b.id)+'.html',documentHTML(b,true));
 add('entries.csv',csv([['รหัส','ประเภท','วันที่เอกสาร','ครบกำหนด','คู่ค้า','เลขเอกสาร','หมวด','รายละเอียด','ยอดรวม','VAT ตามเอกสาร','ผู้รับผิดชอบ','ยกเลิกเมื่อ','เหตุผล'],...entries.map(e=>[e.id,e.kind,e.document_date,e.due_date,e.counterparty,e.reference,e.category,e.description,money(e.amount),money(e.vat),e.assignee,e.voided_at,e.void_reason])]));
 add('payments.csv',csv([['รหัสชำระ','รหัสรายการ','ประเภท','คู่ค้า','เลขเอกสาร','วันเวลาชำระ','ยอดชำระ','อ้างอิงการโอน','ผู้บันทึก','ยกเลิกเมื่อ','เหตุผล'],...payments.map(p=>[p.id,p.entry_id,p.kind,p.counterparty,p.document_reference,p.paid_at,money(p.amount),p.reference,p.actor,p.voided_at,p.void_reason])]));
 add('order-receipts.csv',csv([['ออเดอร์','ลูกค้า','เวลารับเงิน','ยอดรับรวม','VAT สินค้า','ค่าขนส่ง','หมายเหตุ'],...orders.map(o=>[orderNumber(o),o.customer,o.transferred_at||o.created,money(o.total),money(o.vat),money(o.shipping),o.transferred_at?'':'ไม่ระบุเวลาโอน ใช้วันสั่งซื้อชั่วคราว'])]));
 if(q.get('images')==='1'){
 const images=(await db().prepare('SELECT f.* FROM accounting_files f JOIN accounting_entries e ON e.id=f.entry_id WHERE e.document_date>=?::date AND e.document_date<=?::date ORDER BY f.entry_id,f.id LIMIT 501').bind(from,through).all()).results;if(images.length>500)throw Error('ภาพแนบมากเกินไป กรุณาลดช่วงวันที่');
 for(const f of images){const object=await storageBucket.get(f.storage_key);if(!object)throw Error('โหลดภาพแนบบางไฟล์ไม่สำเร็จ กรุณาลองใหม่');const reader=object.body.getReader(),chunks:Uint8Array[]=[];let bytes=0;while(true){const part=await reader.read();if(part.done)break;bytes+=part.value.length;if(size+bytes>3500000){await reader.cancel();throw Error('ภาพแนบรวมเกิน 3.5 MB กรุณาไม่รวมภาพแล้วดาวน์โหลดแยก')}chunks.push(part.value)}add('attachments/'+f.entry_id+'/'+f.id+(f.mime==='image/png'?'.png':f.mime==='image/webp'?'.webp':'.jpg'),Buffer.concat(chunks))}
 }
 add('README-TH.txt',`ชุดเอกสารบัญชี FACTORBOXES ${from} ถึง ${through}\nยอดเงินใน CSV เป็นบาท\nเอกสาร HTML เปิดดูได้โดยไม่ต้องเข้าสู่ระบบ กดพิมพ์ / บันทึก PDF ได้\ndocuments และ bills เลือกตามวันที่ออก; entries และภาพแนบเลือกตามวันที่เอกสาร; payments และ order-receipts เลือกตามเวลาชำระ\nใบเสร็จและใบกำกับอาจอ้างถึงออเดอร์เดียวกัน ห้ามบวกยอดเอกสารทั้งสองเป็นรายได้ซ้ำ\norder-receipts นับออเดอร์ครั้งเดียว รวมยอดรับเงิน; payments เป็นรายรับอื่น/รายจ่ายนอกออเดอร์\nรายการยกเลิกยังอยู่ในรายงานเพื่อให้นักบัญชีตรวจสอบ ให้ตัดออกก่อนสรุปยอด\nVAT รายจ่ายคือจำนวนตามเอกสารที่กรอก ไม่ใช่การรับรองสิทธินำไปเครดิตภาษี\nชุดนี้เป็นทะเบียนเอกสารและรับจ่าย ไม่ใช่งบทดลองหรือแบบยื่นภาษี\nภาพแนบ: ${q.get('images')==='1'?'รวมแล้ว':'ไม่ได้รวม ดาวน์โหลดเพิ่มจากรายการบัญชี'}\n`);
 const zip=zipFiles(files);return new Response(new Uint8Array(zip),{headers:{'Content-Type':'application/zip','Content-Disposition':`attachment; filename="FACTORBOXES-accounting-${from}-${through}.zip"`,'Cache-Control':'private, no-store'}});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'ส่งออกไม่สำเร็จ'},{status:400})}}
